// @vitest-environment jsdom
import { act, cleanup, fireEvent, render } from '@testing-library/react'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import { VideoEditSequenceDialog } from './VideoEditSequenceDialog'
import { useSettingsStore } from '@/stores/settingsStore'
import { VIDEO_EDIT_SEQUENCE_DEFAULTS } from '@/core/videoEdit/sequenceDefaults'
import type { VideoEditSequenceSettings } from '../application/videoEditProjectItems'
beforeEach(() => {
  useSettingsStore.getState().setVideoEditSequenceDefaults(structuredClone(VIDEO_EDIT_SEQUENCE_DEFAULTS))
  vi.spyOn(HTMLCanvasElement.prototype, 'getContext').mockReturnValue(null)
})
afterEach(() => { cleanup(); vi.restoreAllMocks(); useSettingsStore.getState().setVideoEditSequenceDefaults(structuredClone(VIDEO_EDIT_SEQUENCE_DEFAULTS)) })
function dialog(initial: VideoEditSequenceSettings = {}, requireFrameRate = false, mode: 'create' | 'edit' = 'create') {
  const submit = vi.fn(); const close = vi.fn()
  const view = render(<VideoEditSequenceDialog title={mode === 'edit' ? '序列设置' : '新建序列'} mode={mode} initial={initial} bins={[]} requireFrameRate={requireFrameRate} onClose={close} onSubmit={submit} />)
  return { ...view, submit, close }
}
function select(view: ReturnType<typeof dialog>, label: string, option: string): void {
  fireEvent.click(view.getByRole('button', { name: label }))
  fireEvent.click(view.getByRole('option', { name: option }))
}
function dimensions(view: ReturnType<typeof dialog>, width: string, height: string): void {
  expect(view.getByLabelText('宽度')).toHaveProperty('value', width)
  expect(view.getByLabelText('高度')).toHaveProperty('value', height)
}
it('比例和档位下拉换算8K竖屏，高帧率仍输出有理数；尺寸和素材箱始终可见', async () => {
  const view = dialog()
  expect(view.getByLabelText('序列素材箱')).toBeTruthy()
  dimensions(view, '1920', '1080')
  select(view, '画面比例', '9:16'); select(view, '分辨率', '8K'); select(view, '帧率', '120 帧')
  dimensions(view, '4320', '7680')
  await act(async () => fireEvent.click(view.getByRole('button', { name: '新建' })))
  expect(view.submit).toHaveBeenCalledWith(expect.objectContaining({ width: 4320, height: 7680, frameRate: { numerator: 120, denominator: 1 }, binId: null }))
})
it('宽高直接编辑反推组合；比例近似时仅档位自定义，独立编辑后两者自定义', () => {
  const view = dialog()
  fireEvent.change(view.getByLabelText('宽度'), { target: { value: '3840' } })
  dimensions(view, '3840', '2160')
  expect(view.getByRole('button', { name: '画面比例' }).textContent).toBe('16:9')
  expect(view.getByRole('button', { name: '分辨率' }).textContent).toBe('4K')
  fireEvent.change(view.getByLabelText('宽度'), { target: { value: '2000' } })
  expect(view.getByRole('button', { name: '画面比例' }).textContent).toBe('16:9')
  expect(view.getByRole('button', { name: '分辨率' }).textContent).toBe('自定义')
  fireEvent.click(view.getByRole('button', { name: '锁定比例' }))
  fireEvent.change(view.getByLabelText('高度'), { target: { value: '1000' } })
  dimensions(view, '2000', '1000')
  expect(view.getByRole('button', { name: '画面比例' }).textContent).toBe('自定义')
})
it('默认锁定，宽高双向跟随；解锁后独立，重新锁定使用当前比例', () => {
  const view = dialog()
  const lock = view.getByRole('button', { name: '锁定比例' })
  expect(lock.getAttribute('aria-pressed')).toBe('true')
  fireEvent.change(view.getByLabelText('高度'), { target: { value: '720' } }); dimensions(view, '1280', '720')
  fireEvent.click(lock); expect(lock.getAttribute('aria-pressed')).toBe('false')
  fireEvent.change(view.getByLabelText('宽度'), { target: { value: '1440' } }); dimensions(view, '1440', '720')
  fireEvent.click(lock)
  fireEvent.change(view.getByLabelText('高度'), { target: { value: '1000' } }); dimensions(view, '2000', '1000')
})
it('非整比档位锁定实际宽高比，未编辑的失焦不改变尺寸或档位，空输入不会被另一边编辑覆盖', () => {
  const view = dialog()
  select(view, '画面比例', '4:3'); dimensions(view, '1662', '1248')
  fireEvent.blur(view.getByLabelText('宽度')); dimensions(view, '1662', '1248')
  expect(view.getByRole('button', { name: '分辨率' }).textContent).toBe('1080p')
  fireEvent.change(view.getByLabelText('宽度'), { target: { value: '3324' } }); dimensions(view, '3324', '2496')
  fireEvent.click(view.getByRole('button', { name: '锁定比例' }))
  fireEvent.change(view.getByLabelText('高度'), { target: { value: '' } })
  fireEvent.change(view.getByLabelText('宽度'), { target: { value: '2000' } }); dimensions(view, '2000', '')
  expect(view.getByText('宽高至少 16')).toBeTruthy()
})
it('选自定义不改尺寸且聚焦宽度；只失焦不清掉主动选择，编辑与失焦取偶数后反推', () => {
  const view = dialog()
  select(view, '分辨率', '自定义'); dimensions(view, '1920', '1080')
  expect(document.activeElement).toBe(view.getByLabelText('宽度'))
  fireEvent.blur(view.getByLabelText('宽度'))
  expect(view.getByRole('button', { name: '分辨率' }).textContent).toBe('自定义')
  select(view, '画面比例', '自定义'); dimensions(view, '1920', '1080')
  expect(document.activeElement).toBe(view.getByLabelText('宽度'))
  fireEvent.change(view.getByLabelText('宽度'), { target: { value: '1919' } }); dimensions(view, '1919', '1080')
  fireEvent.change(view.getByLabelText('宽度'), { target: { value: '1919.4' } }); dimensions(view, '1919.4', '1080')
  expect(view.queryByText('超过 8K 上限')).toBeNull()
  fireEvent.blur(view.getByLabelText('宽度')); dimensions(view, '1920', '1080')
  expect(view.getByRole('button', { name: '分辨率' }).textContent).toBe('1080p')
})
it('自定义档位切比例保持当前总像素；自定义比例切档位保持当前宽高比', () => {
  const view = dialog({ width: 1440, height: 1440 })
  select(view, '分辨率', '自定义'); select(view, '画面比例', '9:16'); dimensions(view, '1080', '1920')
  cleanup()
  const custom = dialog({ width: 2400, height: 1000 })
  expect(custom.getByRole('button', { name: '画面比例' }).textContent).toBe('自定义')
  expect(custom.getByLabelText('序列预览').textContent).toBe('12:5')
  select(custom, '分辨率', '4K'); dimensions(custom, '4462', '1860')
  expect(custom.getByRole('button', { name: '画面比例' }).textContent).toBe('自定义')
})
it('超宽8K档位禁用、4:3 的 8K 取偶后仍可用，提示超过上限；合法8K有性能tooltip', () => {
  const view = dialog()
  fireEvent.click(view.getByRole('button', { name: '分辨率' }))
  const eight = view.getByRole('option', { name: '8K' })
  fireEvent.focus(eight)
  expect(view.getByRole('tooltip').textContent).toBe('预览可能较吃力，可在节目监视器降低回放分辨率')
  fireEvent.click(eight)
  select(view, '画面比例', '21:9'); dimensions(view, '8798', '3770')
  expect(view.getByRole('button', { name: '新建' })).toHaveProperty('disabled', true)
  fireEvent.click(view.getByRole('button', { name: '分辨率' }))
  const disabled = view.getByRole('option', { name: '8K' })
  expect(disabled).toHaveProperty('disabled', true)
  fireEvent.focus(disabled.parentElement!)
  expect(view.getByRole('tooltip').textContent).toBe('超过 8K 上限')
  fireEvent.click(disabled); dimensions(view, '8798', '3770')
  cleanup()
  const square = dialog({ width: 1440, height: 1440 })
  expect(square.getByLabelText('序列预览').textContent).toBe('')
  select(square, '画面比例', '4:3')
  fireEvent.click(square.getByRole('button', { name: '分辨率' }))
  expect(square.getByRole('option', { name: '8K' })).toHaveProperty('disabled', false)
})
it.each([{ width: '8194', height: '1000', error: '超过 8K 上限' }, { width: '6000', height: '6000', error: '超过 8K 上限' }, { width: '14', height: '720', error: '宽高至少 16' }])('非法尺寸即时提示并禁用提交与保存默认 %j', async ({ width, height, error }) => {
  const view = dialog()
  fireEvent.click(view.getByRole('button', { name: '锁定比例' }))
  fireEvent.change(view.getByLabelText('宽度'), { target: { value: width } }); fireEvent.change(view.getByLabelText('高度'), { target: { value: height } })
  expect(view.getByText(error)).toBeTruthy()
  expect(view.getByRole('button', { name: '新建' })).toHaveProperty('disabled', true)
  expect(view.getByRole('button', { name: '保存为默认值' })).toHaveProperty('disabled', true)
  await act(async () => fireEvent.click(view.getByRole('button', { name: '新建' })))
  expect(view.submit).not.toHaveBeenCalled()
  expect(useSettingsStore.getState().videoEditSequenceDefaults).toEqual(VIDEO_EDIT_SEQUENCE_DEFAULTS)
  fireEvent.change(view.getByLabelText('宽度'), { target: { value: '8192' } }); fireEvent.change(view.getByLabelText('高度'), { target: { value: '4000' } })
  expect(view.queryByText(error)).toBeNull()
  await act(async () => fireEvent.click(view.getByRole('button', { name: '新建' })))
  expect(view.submit).toHaveBeenCalledWith(expect.objectContaining({ width: 8192, height: 4000 }))
})
it('更多设置默认折叠，保存全部默认规格；未改值保留已保存状态，改任意字段后恢复', () => {
  const view = dialog()
  expect(view.queryByLabelText('像素长宽比')).toBeNull()
  fireEvent.click(view.getByRole('button', { name: '更多设置' }))
  fireEvent.change(view.getByLabelText('像素长宽比'), { target: { value: '4/3' } })
  fireEvent.change(view.getByLabelText('音频采样率'), { target: { value: '44100' } })
  fireEvent.change(view.getByLabelText('声道'), { target: { value: '1' } })
  select(view, '帧率', '100 帧')
  fireEvent.click(view.getByRole('button', { name: '保存为默认值' }))
  expect(useSettingsStore.getState().videoEditSequenceDefaults).toMatchObject({ frameRate: { numerator: 100, denominator: 1 }, pixelAspectRatio: { numerator: 4, denominator: 3 }, sampleRate: 44100, channels: 1 })
  expect(view.getByRole('button', { name: '已保存为默认值' })).toBeTruthy()
  select(view, '帧率', '100 帧')
  expect(view.getByRole('button', { name: '已保存为默认值' })).toBeTruthy()
  fireEvent.change(view.getByLabelText('序列名称'), { target: { value: '新名称' } })
  expect(view.getByRole('button', { name: '保存为默认值' })).toBeTruthy()
})
it('序列设置的主按钮为保存', async () => {
  const view = dialog({ name: '已有序列', frameRate: { numerator: 60000, denominator: 1000 } }, false, 'edit')
  expect(view.getByRole('button', { name: '帧率' }).textContent).toBe('60 帧')
  expect(view.queryByRole('button', { name: '新建' })).toBeNull()
  await act(async () => fireEvent.click(view.getByRole('button', { name: '保存' })))
  expect(view.submit).toHaveBeenCalledWith(expect.objectContaining({ name: '已有序列', frameRate: { numerator: 60000, denominator: 1000 } }))
})
it('不可靠素材帧率预选60帧，点击主按钮即确认，无需另外改选', async () => {
  const view = dialog({ frameRate: { numerator: 24, denominator: 1 } }, true)
  expect(view.getByRole('button', { name: '帧率' }).textContent).toBe('60 帧')
  fireEvent.click(view.getByRole('button', { name: '保存为默认值' }))
  expect(useSettingsStore.getState().videoEditSequenceDefaults.frameRate).toEqual({ numerator: 60, denominator: 1 })
  await act(async () => fireEvent.click(view.getByRole('button', { name: '新建' })))
  expect(view.submit).toHaveBeenCalledWith(expect.objectContaining({ frameRate: { numerator: 60, denominator: 1 } }))
})
