export const PROTECTED_APPLICATION_SETTING_DEFINITIONS: Record<string, Record<string, unknown>> = {
  'security.provider_keys': {
    id: 'security.provider_keys',
    title: '服务密钥',
    description: '只能查询各服务是否已配置；密钥值永不返回给助手。',
    aliases: ['API Key', '密钥', '供应商密钥'],
    target: { tab: 'api', sectionId: 'api-keys' },
    sensitive: true,
    writable: false,
  },
  'storage.download_paths': {
    id: 'storage.download_paths',
    title: '下载目录',
    description: '只能查询是否已配置；选择或迁移目录必须由系统选择器和用户完成。',
    aliases: ['下载路径', '保存目录', '本地路径'],
    target: { tab: 'general', sectionId: 'general-storage' },
    sensitive: true,
    writable: false,
  },
  'storage.data_path': {
    id: 'storage.data_path',
    title: '应用数据目录',
    description: '可以定位到数据目录设置；迁移目录必须通过系统确认完成。',
    aliases: ['数据目录', '迁移数据', '存储位置'],
    target: { tab: 'general', sectionId: 'general-storage' },
    sensitive: true,
    writable: false,
  },
  'downloads.quick_path': {
    id: 'downloads.quick_path',
    title: '快速下载目录',
    description: '可以定位到下载目录设置；具体路径只能通过系统选择器确认。',
    aliases: ['快速下载路径', '下载文件夹'],
    target: { tab: 'general', sectionId: 'general-storage' },
    sensitive: true,
    writable: false,
  },
  'models.visibility': {
    id: 'models.visibility',
    title: '模型显示范围',
    description: '可以定位到模型管理；具体模型选择由用户在列表中确认。',
    aliases: ['隐藏模型', '显示模型', '模型管理'],
    target: { tab: 'models', sectionId: 'models-visibility' },
    sensitive: false,
    writable: false,
  },
  'llm.configuration': {
    id: 'llm.configuration',
    title: '助手模型配置',
    description: '可以定位到助手模型配置；密钥值不会提供给助手。',
    aliases: ['大语言模型', '助手模型', 'LLM 配置'],
    target: { tab: 'api', sectionId: 'api-llm' },
    sensitive: true,
    writable: false,
  },
  'updates.configuration': {
    id: 'updates.configuration',
    title: '软件更新',
    description: '可以定位到软件更新与维护设置。',
    aliases: ['检查更新', '自动更新', '维护'],
    target: { tab: 'general', sectionId: 'general-maintenance' },
    sensitive: false,
    writable: false,
  },
}
