/** 由 scripts/generate-catalog-index.cjs 自动生成；只聚合当前供应商的真实模型文件。 */
import model1 from '../../catalog/fal/gemini-omni-flash.model'
import model2 from '../../catalog/fal/gpt-image-2.model'
import model3 from '../../catalog/fal/grok-imagine-2.0.model'
import model4 from '../../catalog/fal/hailuo-02.model'
import model5 from '../../catalog/fal/hailuo-2.3.model'
import model6 from '../../catalog/fal/kling-3.0-omni.model'
import model7 from '../../catalog/fal/kling-3.0-turbo.model'
import model8 from '../../catalog/fal/kling-3.0.model'
import model9 from '../../catalog/fal/kling-image-o1.model'
import model10 from '../../catalog/fal/kling-video-o1.model'
import model11 from '../../catalog/fal/kling-video-v2.6-pro.model'
import model12 from '../../catalog/fal/ltx-2.model'
import model13 from '../../catalog/fal/minimax-h3.model'
import model14 from '../../catalog/fal/nano-banana-2.model'
import model15 from '../../catalog/fal/nano-banana-pro.model'
import model16 from '../../catalog/fal/nano-banana.model'
import model17 from '../../catalog/fal/pixverse-v5.5.model'
import model18 from '../../catalog/fal/qwen-image-3.0.model'
import model19 from '../../catalog/fal/seedance-2.0-fast.model'
import model20 from '../../catalog/fal/seedance-2.0-mini.model'
import model21 from '../../catalog/fal/seedance-2.0.model'
import model22 from '../../catalog/fal/seedance-2.5.model'
import model23 from '../../catalog/fal/seedance.model'
import model24 from '../../catalog/fal/seedream-5.0-lite.model'
import model25 from '../../catalog/fal/seedream-5.0-pro.model'
import model26 from '../../catalog/fal/seedream-v4.5.model'
import model27 from '../../catalog/fal/seedream-v4.model'
import model28 from '../../catalog/fal/veo-3.1.model'
import model29 from '../../catalog/fal/vidu-q2.model'
import model30 from '../../catalog/fal/wan-2.5-preview.model'
import model31 from '../../catalog/fal/z-image-turbo.model'
import { provider } from '../provider-adapters/fal'
import type { GenerationPack } from '../../generation/core'

export const models = [model1, model2, model3, model4, model5, model6, model7, model8, model9, model10, model11, model12, model13, model14, model15, model16, model17, model18, model19, model20, model21, model22, model23, model24, model25, model26, model27, model28, model29, model30, model31] as const
export const pack: GenerationPack = { models, providers: [provider] }
export default pack
