/** 由 scripts/generate-catalog-index.cjs 自动生成；只聚合当前供应商的真实模型文件。 */
import model1 from '../../catalog/kie/gemini-omni-video.model'
import model2 from '../../catalog/kie/gpt-image-2.model'
import model3 from '../../catalog/kie/grok-imagine-2.0.model'
import model4 from '../../catalog/kie/grok-imagine-video.model'
import model5 from '../../catalog/kie/grok-imagine.model'
import model6 from '../../catalog/kie/hailuo-02.model'
import model7 from '../../catalog/kie/hailuo-2-3.model'
import model8 from '../../catalog/kie/kling-3.0-omni.model'
import model9 from '../../catalog/kie/kling-3.0-turbo.model'
import model10 from '../../catalog/kie/kling-3.0.model'
import model11 from '../../catalog/kie/kling-v2-6.model'
import model12 from '../../catalog/kie/minimax-h3.model'
import model13 from '../../catalog/kie/nano-banana-2-lite.model'
import model14 from '../../catalog/kie/nano-banana-2.model'
import model15 from '../../catalog/kie/nano-banana-pro.model'
import model16 from '../../catalog/kie/qwen-image-3.0.model'
import model17 from '../../catalog/kie/seedance-1.5-pro.model'
import model18 from '../../catalog/kie/seedance-2.0-fast.model'
import model19 from '../../catalog/kie/seedance-2.0-mini.model'
import model20 from '../../catalog/kie/seedance-2.0.model'
import model21 from '../../catalog/kie/seedance-2.5.model'
import model22 from '../../catalog/kie/seedance-v1.model'
import model23 from '../../catalog/kie/seedream-4.0.model'
import model24 from '../../catalog/kie/seedream-4.5.model'
import model25 from '../../catalog/kie/seedream-5.0-lite.model'
import model26 from '../../catalog/kie/seedream-5.0-pro.model'
import model27 from '../../catalog/kie/z-image.model'
import { provider } from '../provider-adapters/kie'
import type { GenerationPack } from '../../generation/core'

export const models = [model1, model2, model3, model4, model5, model6, model7, model8, model9, model10, model11, model12, model13, model14, model15, model16, model17, model18, model19, model20, model21, model22, model23, model24, model25, model26, model27] as const
export const pack: GenerationPack = { models, providers: [provider] }
export default pack
