import { z } from 'zod'

import { imageEditOperationSchema } from '../../../../../../src/core/assistant/imageEditContracts'
import { defineAgentTool } from '../define-tool'
import type { AgentToolDefinition } from '../types'
import { eraseToolDefinition, expectedRevision, requireFrontendSuccess, type FrontendToolInvoker } from './frontend-utils'

const revisionOutput = { revision: z.number().int().nonnegative(), scopeRevisions: z.record(z.string(), z.number()) }
const objectType = z.enum(['primitive', 'character', 'camera'])
const primitiveKind = z.enum(['box', 'sphere', 'cylinder', 'cone', 'pyramid', 'torus'])

export function createFrontendToolboxTools(invoke: FrontendToolInvoker): AgentToolDefinition[] {
  const listTools = defineAgentTool({
    name: 'list_toolbox_tools', version: 1, title: '列出工具箱能力', description: '列出工具箱内可通过语义参数使用的工具及能力边界。', category: 'toolbox', side: 'frontend', risk: 'R0', permission: 'toolbox:read', readOnly: true, destructive: false, openWorld: false, idempotent: true, timeoutMs: 5_000, retryPolicy: { maxRetries: 1, baseDelayMs: 100 }, supportsPreview: false, supportsUndo: false, requiredContext: [],
    inputSchema: z.object({}).strict(), outputSchema: z.object({ tools: z.array(z.record(z.string(), z.unknown())), ...revisionOutput }).passthrough(), aiInputSchema: { type: 'object', properties: {}, additionalProperties: false },
    execute: async (_input, context) => requireFrontendSuccess(await invoke({ kind: 'query', query: { name: 'list_toolbox_tools', input: {} } }, context)), concurrencyKey: () => 'toolbox_catalog', targetIds: () => ({}), dataClasses: () => ['C0'], summarize: (output) => `工具箱提供 ${Array.isArray(output.tools) ? output.tools.length : 0} 个工具。`,
  })
  const toolboxState = defineAgentTool({
    name: 'get_toolbox_state', version: 1, title: '读取工具箱状态', description: '读取当前工具、3D 工程和选择摘要，不返回完整场景。', category: 'toolbox', side: 'frontend', risk: 'R0', permission: 'toolbox:read', readOnly: true, destructive: false, openWorld: false, idempotent: true, timeoutMs: 5_000, retryPolicy: { maxRetries: 1, baseDelayMs: 100 }, supportsPreview: false, supportsUndo: false, requiredContext: [],
    inputSchema: z.object({}).strict(), outputSchema: z.object({ state: z.record(z.string(), z.unknown()), ...revisionOutput }).passthrough(), aiInputSchema: { type: 'object', properties: {}, additionalProperties: false },
    execute: async (_input, context) => requireFrontendSuccess(await invoke({ kind: 'query', query: { name: 'get_toolbox_state', input: {} } }, context)), concurrencyKey: () => 'toolbox_state', targetIds: () => ({}), dataClasses: () => ['C0'], summarize: () => '已读取工具箱状态。',
  })
  const selectTool = defineAgentTool({
    name: 'select_toolbox_tool', version: 1, title: '切换工具箱工具', description: '按稳定工具 ID 打开或关闭工具箱子工具，不模拟点击。', category: 'toolbox', side: 'frontend', risk: 'R0', permission: 'toolbox:write', readOnly: false, destructive: false, openWorld: false, idempotent: true, timeoutMs: 5_000, retryPolicy: { maxRetries: 1, baseDelayMs: 100 }, supportsPreview: false, supportsUndo: false, requiredContext: ['toolbox'],
    inputSchema: z.object({ toolId: z.enum(['cameraStage', 'imageMark']).nullable() }).strict(), outputSchema: z.object({ toolId: z.string().nullable(), ...revisionOutput }).passthrough(), aiInputSchema: { type: 'object', properties: { toolId: { type: ['string', 'null'], enum: ['cameraStage', 'imageMark', null] } }, required: ['toolId'], additionalProperties: false },
    execute: async (input, context) => requireFrontendSuccess(await invoke({ kind: 'command', command: { name: 'select_toolbox_tool', input, expectedRevisions: expectedRevision(context.hostContext?.scopeRevisions, ['toolbox']) } }, context)), concurrencyKey: () => 'toolbox_selection', targetIds: (input) => ({ toolId: input.toolId ?? '' }), dataClasses: () => ['C0'], summarize: (output) => `当前工具：${String(output.toolId ?? '工具箱首页')}。`,
  })
  const listCameraProjects = defineAgentTool({
    name: 'list_camera_stage_projects', version: 1, title: '列出 3D 运镜工程', description: '列出 3D 镜头参考工程摘要。', category: 'camera_stage', side: 'frontend', risk: 'R0', permission: 'camera_stage:read', readOnly: true, destructive: false, openWorld: false, idempotent: true, timeoutMs: 8_000, retryPolicy: { maxRetries: 1, baseDelayMs: 100 }, supportsPreview: false, supportsUndo: false, requiredContext: [],
    inputSchema: z.object({}).strict(), outputSchema: z.object({ projects: z.array(z.record(z.string(), z.unknown())), ...revisionOutput }).passthrough(), aiInputSchema: { type: 'object', properties: {}, additionalProperties: false }, execute: async (_input, context) => requireFrontendSuccess(await invoke({ kind: 'query', query: { name: 'list_camera_stage_projects', input: {} } }, context)), concurrencyKey: () => 'camera_stage_catalog', targetIds: () => ({}), dataClasses: () => ['C1'], summarize: (output) => `3D 运镜工程目录返回 ${Array.isArray(output.projects) ? output.projects.length : 0} 项。`,
  })
  const getCameraProject = defineAgentTool({
    name: 'get_camera_stage_project', version: 1, title: '读取 3D 运镜工程', description: '按工程 ID 读取 3D 场景摘要和有限大小的序列化数据。', category: 'camera_stage', side: 'frontend', risk: 'R0', permission: 'camera_stage:read', readOnly: true, destructive: false, openWorld: false, idempotent: true, timeoutMs: 8_000, retryPolicy: { maxRetries: 1, baseDelayMs: 100 }, supportsPreview: false, supportsUndo: false, requiredContext: [],
    inputSchema: z.object({ projectId: z.string().min(1) }).strict(), outputSchema: z.object({ project: z.record(z.string(), z.unknown()), ...revisionOutput }).passthrough(), aiInputSchema: { type: 'object', properties: { projectId: { type: 'string' } }, required: ['projectId'], additionalProperties: false }, execute: async (input, context) => requireFrontendSuccess(await invoke({ kind: 'query', query: { name: 'get_camera_stage_project', input } }, context)), concurrencyKey: (input) => `camera_stage_project:${input.projectId}`, targetIds: (input) => ({ projectId: input.projectId }), dataClasses: () => ['C1'], summarize: (output) => `已读取 3D 运镜工程 ${String((output.project as Record<string, unknown>).id ?? '')}。`,
  })
  const openCameraProject = defineAgentTool({
    name: 'open_camera_stage_project', version: 1, title: '打开 3D 运镜工程', description: '打开明确 3D 工程并进入工具箱编辑器。', category: 'camera_stage', side: 'frontend', risk: 'R1', permission: 'camera_stage:open', readOnly: false, destructive: false, openWorld: false, idempotent: true, timeoutMs: 15_000, retryPolicy: { maxRetries: 1, baseDelayMs: 100 }, supportsPreview: false, supportsUndo: false, requiredContext: ['toolbox'],
    inputSchema: z.object({ projectId: z.string().min(1) }).strict(), outputSchema: z.object({ projectId: z.string(), objectCount: z.number(), shotCount: z.number(), ...revisionOutput }).passthrough(), aiInputSchema: { type: 'object', properties: { projectId: { type: 'string' } }, required: ['projectId'], additionalProperties: false }, execute: async (input, context) => requireFrontendSuccess(await invoke({ kind: 'command', command: { name: 'open_camera_stage_project', input, expectedRevisions: expectedRevision(context.hostContext?.scopeRevisions, ['toolbox']) } }, context)), concurrencyKey: () => 'camera_stage_open', targetIds: (input) => ({ projectId: input.projectId }), dataClasses: () => ['C1'], summarize: (output) => `已打开 3D 运镜工程 ${String(output.projectId)}。`,
  })
  const createCameraProject = defineAgentTool({
    name: 'create_camera_stage_project', version: 1, title: '新建 3D 运镜工程', description: '创建 3D 运镜工程并进入编辑器。', category: 'camera_stage', side: 'frontend', risk: 'R1', permission: 'camera_stage:write', readOnly: false, destructive: false, openWorld: false, idempotent: false, timeoutMs: 15_000, retryPolicy: { maxRetries: 0, baseDelayMs: 0 }, supportsPreview: false, supportsUndo: false, requiredContext: ['toolbox'],
    inputSchema: z.object({ name: z.string().trim().min(1).max(120), mode: z.enum(['simple', 'pro']).default('simple') }).strict(), outputSchema: z.object({ projectId: z.string(), name: z.string(), mode: z.enum(['simple', 'pro']), ...revisionOutput }).passthrough(), aiInputSchema: { type: 'object', properties: { name: { type: 'string' }, mode: { type: 'string', enum: ['simple', 'pro'] } }, required: ['name'], additionalProperties: false }, execute: async (input, context) => requireFrontendSuccess(await invoke({ kind: 'command', command: { name: 'create_camera_stage_project', input, expectedRevisions: expectedRevision(context.hostContext?.scopeRevisions, ['toolbox']) } }, context)), concurrencyKey: () => 'camera_stage_project', targetIds: (input) => ({ name: input.name }), dataClasses: () => ['C1'], summarize: (output) => `已创建 3D 运镜工程 ${String(output.projectId)}。`,
  })
  const renameCameraProject = defineAgentTool({
    name: 'rename_camera_stage_project', version: 1, title: '重命名 3D 运镜工程', description: '重命名明确的 3D 运镜工程。', category: 'camera_stage', side: 'frontend', risk: 'R1', permission: 'camera_stage:write', readOnly: false, destructive: false, openWorld: false, idempotent: true, timeoutMs: 10_000, retryPolicy: { maxRetries: 0, baseDelayMs: 0 }, supportsPreview: false, supportsUndo: false, requiredContext: ['toolbox'],
    inputSchema: z.object({ projectId: z.string().min(1), name: z.string().trim().min(1).max(120) }).strict(), outputSchema: z.object({ projectId: z.string(), name: z.string(), ...revisionOutput }).passthrough(), aiInputSchema: { type: 'object', properties: { projectId: { type: 'string' }, name: { type: 'string' } }, required: ['projectId', 'name'], additionalProperties: false }, execute: async (input, context) => requireFrontendSuccess(await invoke({ kind: 'command', command: { name: 'rename_camera_stage_project', input, expectedRevisions: expectedRevision(context.hostContext?.scopeRevisions, ['toolbox']) } }, context)), concurrencyKey: (input) => `camera_stage_project:${input.projectId}`, targetIds: (input) => ({ projectId: input.projectId }), dataClasses: () => ['C1'], summarize: (output) => `已重命名 3D 运镜工程 ${String(output.projectId)}。`,
  })
  const deleteCameraProject = defineAgentTool({
    name: 'delete_camera_stage_project', version: 1, title: '删除 3D 运镜工程', description: '永久删除明确的 3D 运镜工程及其场景数据；不可撤销，必须审批。', category: 'camera_stage', side: 'frontend', risk: 'R3', permission: 'camera_stage:delete', readOnly: false, destructive: true, openWorld: false, idempotent: true, timeoutMs: 15_000, retryPolicy: { maxRetries: 0, baseDelayMs: 0 }, supportsPreview: true, supportsUndo: false, requiredContext: ['toolbox'],
    inputSchema: z.object({ projectId: z.string().min(1) }).strict(), outputSchema: z.object({ projectId: z.string(), status: z.literal('deleted'), ...revisionOutput }).passthrough(), aiInputSchema: { type: 'object', properties: { projectId: { type: 'string' } }, required: ['projectId'], additionalProperties: false }, preview: (input) => ({ title: '删除 3D 运镜工程', summary: `永久删除工程 ${input.projectId}；此操作不可撤销。`, targetIds: { projectId: input.projectId }, reversible: false, dataClasses: ['C1'] }), execute: async (input, context) => requireFrontendSuccess(await invoke({ kind: 'command', command: { name: 'delete_camera_stage_project', input, expectedRevisions: expectedRevision(context.hostContext?.scopeRevisions, ['toolbox']) } }, context)), concurrencyKey: (input) => `camera_stage_project:${input.projectId}`, targetIds: (input) => ({ projectId: input.projectId }), dataClasses: () => ['C1'], summarize: (output) => `3D 运镜工程 ${String(output.projectId)} 已删除。`,
  })
  const addObject = defineAgentTool({
    name: 'add_camera_stage_object', version: 1, title: '添加 3D 场景对象', description: '按对象类型和几何预设添加 3D 场景对象，不模拟拖拽。', category: 'camera_stage', side: 'frontend', risk: 'R1', permission: 'camera_stage:write', readOnly: false, destructive: false, openWorld: false, idempotent: false, timeoutMs: 10_000, retryPolicy: { maxRetries: 0, baseDelayMs: 0 }, supportsPreview: false, supportsUndo: true, requiredContext: ['toolbox'],
    inputSchema: z.object({ projectId: z.string().min(1), objectType, primitiveKind: primitiveKind.optional() }).strict(), outputSchema: z.object({ projectId: z.string(), objectId: z.string(), objectType: z.string(), ...revisionOutput }).passthrough(), aiInputSchema: { type: 'object', properties: { projectId: { type: 'string' }, objectType: { type: 'string', enum: ['primitive', 'character', 'camera'] }, primitiveKind: { type: 'string', enum: ['box', 'sphere', 'cylinder', 'cone', 'pyramid', 'torus'] } }, required: ['projectId', 'objectType'], additionalProperties: false }, execute: async (input, context) => requireFrontendSuccess(await invoke({ kind: 'command', command: { name: 'add_camera_stage_object', input, expectedRevisions: expectedRevision(context.hostContext?.scopeRevisions, ['toolbox']) } }, context)), concurrencyKey: (input) => `camera_stage:${input.projectId}`, targetIds: (input) => ({ projectId: input.projectId, objectType: input.objectType }), dataClasses: () => ['C1'], summarize: (output) => `已添加 3D 对象 ${String(output.objectId)}。`,
  })
  const duplicateObject = defineAgentTool({
    name: 'duplicate_camera_stage_object', version: 1, title: '复制 3D 场景对象', description: '复制明确的 3D 场景对象并保存为新对象。', category: 'camera_stage', side: 'frontend', risk: 'R1', permission: 'camera_stage:write', readOnly: false, destructive: false, openWorld: false, idempotent: false, timeoutMs: 10_000, retryPolicy: { maxRetries: 0, baseDelayMs: 0 }, supportsPreview: false, supportsUndo: true, requiredContext: ['toolbox'],
    inputSchema: z.object({ projectId: z.string().min(1), objectId: z.string().min(1) }).strict(), outputSchema: z.object({ projectId: z.string(), objectId: z.string(), duplicatedFromObjectId: z.string(), ...revisionOutput }).passthrough(), aiInputSchema: { type: 'object', properties: { projectId: { type: 'string' }, objectId: { type: 'string' } }, required: ['projectId', 'objectId'], additionalProperties: false }, execute: async (input, context) => requireFrontendSuccess(await invoke({ kind: 'command', command: { name: 'duplicate_camera_stage_object', input, expectedRevisions: expectedRevision(context.hostContext?.scopeRevisions, ['toolbox']) } }, context)), concurrencyKey: (input) => `camera_stage:${input.projectId}`, targetIds: (input) => ({ projectId: input.projectId, objectId: input.objectId }), dataClasses: () => ['C1'], summarize: (output) => `已复制 3D 对象 ${String(output.duplicatedFromObjectId)}，新对象为 ${String(output.objectId)}。`,
  })
  const deleteObject = defineAgentTool({
    name: 'delete_camera_stage_object', version: 1, title: '删除 3D 场景对象', description: '删除明确的 3D 场景对象；不可撤销，必须审批。', category: 'camera_stage', side: 'frontend', risk: 'R3', permission: 'camera_stage:delete', readOnly: false, destructive: true, openWorld: false, idempotent: true, timeoutMs: 10_000, retryPolicy: { maxRetries: 0, baseDelayMs: 0 }, supportsPreview: true, supportsUndo: false, requiredContext: ['toolbox'],
    inputSchema: z.object({ projectId: z.string().min(1), objectId: z.string().min(1) }).strict(), outputSchema: z.object({ projectId: z.string(), objectId: z.string(), status: z.literal('deleted'), ...revisionOutput }).passthrough(), aiInputSchema: { type: 'object', properties: { projectId: { type: 'string' }, objectId: { type: 'string' } }, required: ['projectId', 'objectId'], additionalProperties: false }, preview: (input) => ({ title: '删除 3D 场景对象', summary: `删除对象 ${input.objectId}；此操作不可撤销。`, targetIds: { projectId: input.projectId, objectId: input.objectId }, reversible: false, dataClasses: ['C1'] }), execute: async (input, context) => requireFrontendSuccess(await invoke({ kind: 'command', command: { name: 'delete_camera_stage_object', input, expectedRevisions: expectedRevision(context.hostContext?.scopeRevisions, ['toolbox']) } }, context)), concurrencyKey: (input) => `camera_stage:${input.projectId}:${input.objectId}`, targetIds: (input) => ({ projectId: input.projectId, objectId: input.objectId }), dataClasses: () => ['C1'], summarize: (output) => `3D 对象 ${String(output.objectId)} 已删除。`,
  })
  const updateObject = defineAgentTool({
    name: 'update_camera_stage_object', version: 1, title: '更新 3D 场景对象', description: '按稳定对象 ID 更新名称、可见性、变换或类型专属参数；不改变对象类型。', category: 'camera_stage', side: 'frontend', risk: 'R1', permission: 'camera_stage:write', readOnly: false, destructive: false, openWorld: false, idempotent: true, timeoutMs: 10_000, retryPolicy: { maxRetries: 0, baseDelayMs: 0 }, supportsPreview: false, supportsUndo: true, requiredContext: ['toolbox'],
    inputSchema: z.object({ projectId: z.string().min(1), objectId: z.string().min(1), patch: z.record(z.string(), z.unknown()) }).strict(), outputSchema: z.object({ projectId: z.string(), objectId: z.string(), updatedKeys: z.array(z.string()), ...revisionOutput }).passthrough(), aiInputSchema: { type: 'object', properties: { projectId: { type: 'string' }, objectId: { type: 'string' }, patch: { type: 'object', additionalProperties: true } }, required: ['projectId', 'objectId', 'patch'], additionalProperties: false }, execute: async (input, context) => requireFrontendSuccess(await invoke({ kind: 'command', command: { name: 'update_camera_stage_object', input, expectedRevisions: expectedRevision(context.hostContext?.scopeRevisions, ['toolbox']) } }, context)), concurrencyKey: (input) => `camera_stage:${input.projectId}:${input.objectId}`, targetIds: (input) => ({ projectId: input.projectId, objectId: input.objectId }), dataClasses: () => ['C1'], summarize: (output) => `已更新 3D 对象 ${String(output.objectId)}：${Array.isArray(output.updatedKeys) ? output.updatedKeys.join('、') : '属性'}。`,
  })
  const addShot = defineAgentTool({
    name: 'add_camera_stage_shot', version: 1, title: '添加 3D 镜头卡', description: '在当前 3D 工程捕获一张镜头卡，可指定稳定名称和机位。', category: 'camera_stage', side: 'frontend', risk: 'R1', permission: 'camera_stage:write', readOnly: false, destructive: false, openWorld: false, idempotent: false, timeoutMs: 10_000, retryPolicy: { maxRetries: 0, baseDelayMs: 0 }, supportsPreview: false, supportsUndo: true, requiredContext: ['toolbox'],
    inputSchema: z.object({ projectId: z.string().min(1), name: z.string().trim().min(1).max(120), cameraId: z.string().min(1).nullable().default(null) }).strict(), outputSchema: z.object({ projectId: z.string(), shotId: z.string(), name: z.string(), ...revisionOutput }).passthrough(), aiInputSchema: { type: 'object', properties: { projectId: { type: 'string' }, name: { type: 'string' }, cameraId: { type: ['string', 'null'] } }, required: ['projectId', 'name'], additionalProperties: false }, execute: async (input, context) => requireFrontendSuccess(await invoke({ kind: 'command', command: { name: 'add_camera_stage_shot', input, expectedRevisions: expectedRevision(context.hostContext?.scopeRevisions, ['toolbox']) } }, context)), concurrencyKey: (input) => `camera_stage:${input.projectId}:shots`, targetIds: (input) => ({ projectId: input.projectId, name: input.name }), dataClasses: () => ['C1'], summarize: (output) => `已添加镜头卡 ${String(output.shotId)}。`,
  })
  const updateShot = defineAgentTool({
    name: 'update_camera_stage_shot', version: 1, title: '更新 3D 镜头卡', description: '按稳定 shotId 修改镜头名称、停留、过渡和机位。', category: 'camera_stage', side: 'frontend', risk: 'R1', permission: 'camera_stage:write', readOnly: false, destructive: false, openWorld: false, idempotent: true, timeoutMs: 10_000, retryPolicy: { maxRetries: 0, baseDelayMs: 0 }, supportsPreview: false, supportsUndo: true, requiredContext: ['toolbox'],
    inputSchema: z.object({ projectId: z.string().min(1), shotId: z.string().min(1), patch: z.object({ name: z.string().trim().min(1).max(120).optional(), hold: z.number().min(0).max(3600).optional(), transitionDuration: z.number().min(0).max(3600).optional(), continuity: z.enum(['stop', 'smooth']).optional(), cameraId: z.string().min(1).nullable().optional() }).strict() }).strict(), outputSchema: z.object({ projectId: z.string(), shotId: z.string(), status: z.literal('updated'), ...revisionOutput }).passthrough(), aiInputSchema: { type: 'object', properties: { projectId: { type: 'string' }, shotId: { type: 'string' }, patch: { type: 'object', additionalProperties: true } }, required: ['projectId', 'shotId', 'patch'], additionalProperties: false }, execute: async (input, context) => requireFrontendSuccess(await invoke({ kind: 'command', command: { name: 'update_camera_stage_shot', input, expectedRevisions: expectedRevision(context.hostContext?.scopeRevisions, ['toolbox']) } }, context)), concurrencyKey: (input) => `camera_stage:${input.projectId}:shot:${input.shotId}`, targetIds: (input) => ({ projectId: input.projectId, shotId: input.shotId }), dataClasses: () => ['C1'], summarize: (output) => `已更新镜头卡 ${String(output.shotId)}。`,
  })
  const createImagePreview = defineAgentTool({
    name: 'create_image_edit_preview', version: 1, title: '创建图片编辑预览', description: '对明确图片应用结构化旋转、翻转、裁剪或标记操作，生成不覆盖原图的预览引用。', category: 'image_edit', side: 'frontend', risk: 'R1', permission: 'image_edit:preview', readOnly: false, destructive: false, openWorld: false, idempotent: false, timeoutMs: 30_000, retryPolicy: { maxRetries: 0, baseDelayMs: 0 }, supportsPreview: true, supportsUndo: false, requiredContext: ['toolbox', 'assets'],
    inputSchema: z.object({ assetId: z.string().min(1), operations: z.array(imageEditOperationSchema).min(1).max(32) }).strict(), outputSchema: z.object({ previewRef: z.string(), assetId: z.string(), operationCount: z.number().int().nonnegative(), hasEffect: z.boolean(), width: z.number().positive(), height: z.number().positive(), ...revisionOutput }).passthrough(), aiInputSchema: { type: 'object', properties: { assetId: { type: 'string' }, operations: { type: 'array', minItems: 1, maxItems: 32, items: { type: 'object', properties: { kind: { type: 'string', enum: ['rotate_cw', 'rotate_ccw', 'flip_h', 'flip_v', 'crop', 'mark'] }, degrees: { type: 'integer', minimum: 0, maximum: 360 }, crop: { type: 'object', properties: { x: { type: 'number' }, y: { type: 'number' }, width: { type: 'number', exclusiveMinimum: 0 }, height: { type: 'number', exclusiveMinimum: 0 } }, required: ['x', 'y', 'width', 'height'], additionalProperties: false }, item: { type: 'object', additionalProperties: true } }, required: ['kind'], additionalProperties: false } } }, required: ['assetId', 'operations'], additionalProperties: false }, execute: async (input, context) => requireFrontendSuccess(await invoke({ kind: 'command', command: { name: 'create_image_edit_preview', input, expectedRevisions: expectedRevision(context.hostContext?.scopeRevisions, ['toolbox', 'assets']) } }, context)), concurrencyKey: (input) => `image_edit:${input.assetId}`, targetIds: (input) => ({ assetId: input.assetId }), dataClasses: () => ['C1'], summarize: (output) => `已为素材 ${String(output.assetId)} 创建图片编辑预览 ${String(output.previewRef)}。`,
  })
  const commitImagePreview = defineAgentTool({
    name: 'commit_image_edit', version: 1, title: '保存图片编辑结果', description: '将已创建的图片编辑预览保存为新素材，不覆盖原图。', category: 'image_edit', side: 'frontend', risk: 'R2', permission: 'image_edit:commit', readOnly: false, destructive: false, openWorld: false, idempotent: false, timeoutMs: 60_000, retryPolicy: { maxRetries: 0, baseDelayMs: 0 }, supportsPreview: true, supportsUndo: false, requiredContext: ['toolbox', 'assets'],
    inputSchema: z.object({ previewRef: z.string().min(1), displayName: z.string().trim().max(200).optional() }).strict(), outputSchema: z.object({ previewRef: z.string(), assetId: z.string(), filePath: z.string().optional(), status: z.literal('committed'), ...revisionOutput }).passthrough(), aiInputSchema: { type: 'object', properties: { previewRef: { type: 'string' }, displayName: { type: 'string' } }, required: ['previewRef'], additionalProperties: false }, preview: (input) => ({ title: '保存图片编辑结果', summary: `将预览 ${input.previewRef} 保存为新素材，不覆盖原图。`, targetIds: { previewRef: input.previewRef }, reversible: false, dataClasses: ['C1'] }), execute: async (input, context) => requireFrontendSuccess(await invoke({ kind: 'command', command: { name: 'commit_image_edit', input, expectedRevisions: expectedRevision(context.hostContext?.scopeRevisions, ['toolbox', 'assets']) } }, context)), concurrencyKey: (input) => `image_edit:${input.previewRef}`, targetIds: (input) => ({ previewRef: input.previewRef }), dataClasses: () => ['C1'], summarize: (output) => `图片编辑结果已保存为素材 ${String(output.assetId)}。`,
  })
  const listStoryboardProjects = defineAgentTool({
    name: 'list_storyboard_projects', version: 1, title: '列出分镜项目', description: '列出分镜项目摘要，不返回完整节点和边数据。', category: 'storyboard', side: 'frontend', risk: 'R0', permission: 'storyboard:read', readOnly: true, destructive: false, openWorld: false, idempotent: true, timeoutMs: 8_000, retryPolicy: { maxRetries: 1, baseDelayMs: 100 }, supportsPreview: false, supportsUndo: false, requiredContext: [],
    inputSchema: z.object({}).strict(), outputSchema: z.object({ projects: z.array(z.record(z.string(), z.unknown())), ...revisionOutput }).passthrough(), aiInputSchema: { type: 'object', properties: {}, additionalProperties: false }, execute: async (_input, context) => requireFrontendSuccess(await invoke({ kind: 'query', query: { name: 'list_storyboard_projects', input: {} } }, context)), concurrencyKey: () => 'storyboard_catalog', targetIds: () => ({}), dataClasses: () => ['C1'], summarize: (output) => `分镜项目目录返回 ${Array.isArray(output.projects) ? output.projects.length : 0} 项。`,
  })
  const getStoryboardProject = defineAgentTool({
    name: 'get_storyboard_project', version: 1, title: '读取分镜项目', description: '按项目 ID读取分镜摘要、节点/边计数和受限节点详情。', category: 'storyboard', side: 'frontend', risk: 'R0', permission: 'storyboard:read', readOnly: true, destructive: false, openWorld: false, idempotent: true, timeoutMs: 8_000, retryPolicy: { maxRetries: 1, baseDelayMs: 100 }, supportsPreview: false, supportsUndo: false, requiredContext: [],
    inputSchema: z.object({ projectId: z.string().min(1) }).strict(), outputSchema: z.object({ project: z.record(z.string(), z.unknown()), ...revisionOutput }).passthrough(), aiInputSchema: { type: 'object', properties: { projectId: { type: 'string' } }, required: ['projectId'], additionalProperties: false }, execute: async (input, context) => requireFrontendSuccess(await invoke({ kind: 'query', query: { name: 'get_storyboard_project', input } }, context)), concurrencyKey: (input) => `storyboard_project:${input.projectId}`, targetIds: (input) => ({ projectId: input.projectId }), dataClasses: () => ['C1'], summarize: (output) => `已读取分镜项目 ${String((output.project as Record<string, unknown>).id ?? '')}。`,
  })
  return [eraseToolDefinition(listTools), eraseToolDefinition(toolboxState), eraseToolDefinition(selectTool), eraseToolDefinition(listCameraProjects), eraseToolDefinition(getCameraProject), eraseToolDefinition(openCameraProject), eraseToolDefinition(createCameraProject), eraseToolDefinition(renameCameraProject), eraseToolDefinition(deleteCameraProject), eraseToolDefinition(addObject), eraseToolDefinition(duplicateObject), eraseToolDefinition(deleteObject), eraseToolDefinition(updateObject), eraseToolDefinition(addShot), eraseToolDefinition(updateShot), eraseToolDefinition(createImagePreview), eraseToolDefinition(commitImagePreview), eraseToolDefinition(listStoryboardProjects), eraseToolDefinition(getStoryboardProject)]
}
