import { z } from 'zod'

import { defineAgentTool } from '../define-tool'
import type { AgentToolDefinition } from '../types'
import { eraseToolDefinition, expectedRevision, requireFrontendSuccess, type FrontendToolInvoker } from './frontend-utils'

const revisionOutput = { revision: z.number().int().nonnegative(), scopeRevisions: z.record(z.string(), z.number()) }

export function createFrontendAssetTools(invoke: FrontendToolInvoker): AgentToolDefinition[] {
  const queryAssets = defineAgentTool({
    name: 'query_assets', version: 1, title: '查询素材库', description: '按媒体类型、标签、集合和关键词分页查询素材摘要；不会把本地文件路径放入上下文。', category: 'assets', side: 'frontend', risk: 'R0', permission: 'assets:read', readOnly: true, destructive: false, openWorld: false, idempotent: true, timeoutMs: 8_000, retryPolicy: { maxRetries: 1, baseDelayMs: 100 }, supportsPreview: false, supportsUndo: false, requiredContext: [],
    inputSchema: z.object({ mediaType: z.enum(['image', 'video', 'audio']).optional(), libraryId: z.string().min(1).optional(), tag: z.string().min(1).optional(), keyword: z.string().max(200).optional(), page: z.number().int().min(1).max(1000).default(1), pageSize: z.number().int().min(1).max(50).default(20), sort: z.enum(['created', 'recent']).default('created') }).strict(), outputSchema: z.object({ items: z.array(z.record(z.string(), z.unknown())), total: z.number(), page: z.number(), pageSize: z.number(), ...revisionOutput }).passthrough(), aiInputSchema: { type: 'object', properties: { mediaType: { type: 'string', enum: ['image', 'video', 'audio'] }, libraryId: { type: 'string' }, tag: { type: 'string' }, keyword: { type: 'string' }, page: { type: 'integer', minimum: 1 }, pageSize: { type: 'integer', minimum: 1, maximum: 50 }, sort: { type: 'string', enum: ['created', 'recent'] } }, additionalProperties: false }, execute: async (input, context) => requireFrontendSuccess(await invoke({ kind: 'query', query: { name: 'query_assets', input } }, context)), concurrencyKey: () => 'assets_query', targetIds: (input) => ({ keyword: input.keyword ?? '', libraryId: input.libraryId ?? '' }), dataClasses: () => ['C1'], summarize: (output) => `素材库返回 ${Array.isArray(output.items) ? output.items.length : 0} 项。`,
  })
  const getAsset = defineAgentTool({
    name: 'get_asset', version: 1, title: '读取素材详情', description: '按稳定 assetId 读取单个素材的元数据、标签和集合引用。', category: 'assets', side: 'frontend', risk: 'R0', permission: 'assets:read', readOnly: true, destructive: false, openWorld: false, idempotent: true, timeoutMs: 5_000, retryPolicy: { maxRetries: 1, baseDelayMs: 100 }, supportsPreview: false, supportsUndo: false, requiredContext: [],
    inputSchema: z.object({ assetId: z.string().min(1) }).strict(), outputSchema: z.object({ asset: z.record(z.string(), z.unknown()), ...revisionOutput }).passthrough(), aiInputSchema: { type: 'object', properties: { assetId: { type: 'string' } }, required: ['assetId'], additionalProperties: false }, execute: async (input, context) => requireFrontendSuccess(await invoke({ kind: 'query', query: { name: 'get_asset', input } }, context)), concurrencyKey: (input) => `asset:${input.assetId}`, targetIds: (input) => ({ assetId: input.assetId }), dataClasses: () => ['C1'], summarize: (output) => `已读取素材 ${String((output.asset as Record<string, unknown>).id ?? '')}。`,
  })
  const listLibraries = defineAgentTool({
    name: 'list_asset_libraries', version: 1, title: '列出素材集合', description: '列出素材库集合摘要。', category: 'assets', side: 'frontend', risk: 'R0', permission: 'assets:read', readOnly: true, destructive: false, openWorld: false, idempotent: true, timeoutMs: 5_000, retryPolicy: { maxRetries: 1, baseDelayMs: 100 }, supportsPreview: false, supportsUndo: false, requiredContext: [],
    inputSchema: z.object({}).strict(), outputSchema: z.object({ libraries: z.array(z.record(z.string(), z.unknown())), ...revisionOutput }).passthrough(), aiInputSchema: { type: 'object', properties: {}, additionalProperties: false }, execute: async (_input, context) => requireFrontendSuccess(await invoke({ kind: 'query', query: { name: 'list_asset_libraries', input: {} } }, context)), concurrencyKey: () => 'asset_libraries', targetIds: () => ({}), dataClasses: () => ['C0'], summarize: (output) => `素材集合返回 ${Array.isArray(output.libraries) ? output.libraries.length : 0} 项。`,
  })
  const listTags = defineAgentTool({
    name: 'list_asset_tags', version: 1, title: '列出素材标签', description: '列出已有素材标签，供后续筛选或标记使用。', category: 'assets', side: 'frontend', risk: 'R0', permission: 'assets:read', readOnly: true, destructive: false, openWorld: false, idempotent: true, timeoutMs: 5_000, retryPolicy: { maxRetries: 1, baseDelayMs: 100 }, supportsPreview: false, supportsUndo: false, requiredContext: [],
    inputSchema: z.object({}).strict(), outputSchema: z.object({ tags: z.array(z.string()), ...revisionOutput }).passthrough(), aiInputSchema: { type: 'object', properties: {}, additionalProperties: false }, execute: async (_input, context) => requireFrontendSuccess(await invoke({ kind: 'query', query: { name: 'list_asset_tags', input: {} } }, context)), concurrencyKey: () => 'asset_tags', targetIds: () => ({}), dataClasses: () => ['C0'], summarize: (output) => `素材标签返回 ${Array.isArray(output.tags) ? output.tags.length : 0} 项。`,
  })
  const selectAsset = defineAgentTool({
    name: 'select_asset', version: 1, title: '选择素材', description: '按稳定 assetId 选择素材，供界面跳转或下一步图片编辑使用。', category: 'assets', side: 'frontend', risk: 'R0', permission: 'assets:selection', readOnly: false, destructive: false, openWorld: false, idempotent: true, timeoutMs: 5_000, retryPolicy: { maxRetries: 1, baseDelayMs: 100 }, supportsPreview: false, supportsUndo: false, requiredContext: ['assets'],
    inputSchema: z.object({ assetId: z.string().min(1).nullable() }).strict(), outputSchema: z.object({ assetId: z.string().nullable(), ...revisionOutput }).passthrough(), aiInputSchema: { type: 'object', properties: { assetId: { type: ['string', 'null'] } }, required: ['assetId'], additionalProperties: false }, execute: async (input, context) => requireFrontendSuccess(await invoke({ kind: 'command', command: { name: 'select_asset', input, expectedRevisions: expectedRevision(context.hostContext?.scopeRevisions, ['assets']) } }, context)), concurrencyKey: () => 'asset_selection', targetIds: (input) => ({ assetId: input.assetId ?? '' }), dataClasses: () => ['C1'], summarize: (output) => `当前选中素材：${String(output.assetId ?? '无')}。`,
  })
  const setTags = defineAgentTool({
    name: 'set_asset_tags', version: 1, title: '设置素材标签', description: '覆盖明确素材的标签集合；不会修改原始文件。', category: 'assets', side: 'frontend', risk: 'R1', permission: 'assets:write', readOnly: false, destructive: false, openWorld: false, idempotent: true, timeoutMs: 8_000, retryPolicy: { maxRetries: 0, baseDelayMs: 0 }, supportsPreview: false, supportsUndo: false, requiredContext: ['assets'],
    inputSchema: z.object({ assetId: z.string().min(1), tags: z.array(z.string().trim().min(1).max(80)).max(32) }).strict(), outputSchema: z.object({ assetId: z.string(), tags: z.array(z.string()), ...revisionOutput }).passthrough(), aiInputSchema: { type: 'object', properties: { assetId: { type: 'string' }, tags: { type: 'array', items: { type: 'string' }, maxItems: 32 } }, required: ['assetId', 'tags'], additionalProperties: false }, execute: async (input, context) => requireFrontendSuccess(await invoke({ kind: 'command', command: { name: 'set_asset_tags', input, expectedRevisions: expectedRevision(context.hostContext?.scopeRevisions, ['assets']) } }, context)), concurrencyKey: (input) => `asset:${input.assetId}`, targetIds: (input) => ({ assetId: input.assetId }), dataClasses: () => ['C1'], summarize: (output) => `已更新素材 ${String(output.assetId)} 的标签。`,
  })
  const addToLibrary = defineAgentTool({
    name: 'add_asset_to_library', version: 1, title: '添加素材到集合', description: '把明确素材加入指定集合。', category: 'assets', side: 'frontend', risk: 'R1', permission: 'assets:write', readOnly: false, destructive: false, openWorld: false, idempotent: true, timeoutMs: 8_000, retryPolicy: { maxRetries: 0, baseDelayMs: 0 }, supportsPreview: false, supportsUndo: false, requiredContext: ['assets'], inputSchema: z.object({ libraryId: z.string().min(1), assetId: z.string().min(1) }).strict(), outputSchema: z.object({ libraryId: z.string(), assetId: z.string(), status: z.literal('added'), ...revisionOutput }).passthrough(), aiInputSchema: { type: 'object', properties: { libraryId: { type: 'string' }, assetId: { type: 'string' } }, required: ['libraryId', 'assetId'], additionalProperties: false }, execute: async (input, context) => requireFrontendSuccess(await invoke({ kind: 'command', command: { name: 'add_asset_to_library', input, expectedRevisions: expectedRevision(context.hostContext?.scopeRevisions, ['assets']) } }, context)), concurrencyKey: (input) => `library:${input.libraryId}`, targetIds: (input) => ({ libraryId: input.libraryId, assetId: input.assetId }), dataClasses: () => ['C1'], summarize: (output) => `素材 ${String(output.assetId)} 已加入集合。`,
  })
  const removeFromLibrary = defineAgentTool({
    name: 'remove_asset_from_library', version: 1, title: '从集合移除素材', description: '从指定集合移除明确素材，不删除素材本身。', category: 'assets', side: 'frontend', risk: 'R1', permission: 'assets:write', readOnly: false, destructive: false, openWorld: false, idempotent: true, timeoutMs: 8_000, retryPolicy: { maxRetries: 0, baseDelayMs: 0 }, supportsPreview: false, supportsUndo: false, requiredContext: ['assets'], inputSchema: z.object({ libraryId: z.string().min(1), assetId: z.string().min(1) }).strict(), outputSchema: z.object({ libraryId: z.string(), assetId: z.string(), status: z.literal('removed'), ...revisionOutput }).passthrough(), aiInputSchema: { type: 'object', properties: { libraryId: { type: 'string' }, assetId: { type: 'string' } }, required: ['libraryId', 'assetId'], additionalProperties: false }, execute: async (input, context) => requireFrontendSuccess(await invoke({ kind: 'command', command: { name: 'remove_asset_from_library', input, expectedRevisions: expectedRevision(context.hostContext?.scopeRevisions, ['assets']) } }, context)), concurrencyKey: (input) => `library:${input.libraryId}`, targetIds: (input) => ({ libraryId: input.libraryId, assetId: input.assetId }), dataClasses: () => ['C1'], summarize: (output) => `素材 ${String(output.assetId)} 已从集合移除。`,
  })
  const deleteAsset = defineAgentTool({
    name: 'delete_asset', version: 1, title: '删除素材', description: '永久删除明确素材记录及其受控文件引用；不可撤销，必须审批。', category: 'assets', side: 'frontend', risk: 'R3', permission: 'assets:delete', readOnly: false, destructive: true, openWorld: false, idempotent: true, timeoutMs: 10_000, retryPolicy: { maxRetries: 0, baseDelayMs: 0 }, supportsPreview: true, supportsUndo: false, requiredContext: ['assets'], inputSchema: z.object({ assetId: z.string().min(1) }).strict(), outputSchema: z.object({ assetId: z.string(), status: z.literal('deleted'), ...revisionOutput }).passthrough(), aiInputSchema: { type: 'object', properties: { assetId: { type: 'string' } }, required: ['assetId'], additionalProperties: false }, preview: (input) => ({ title: '删除素材', summary: `永久删除素材 ${input.assetId}；此操作不可撤销。`, targetIds: { assetId: input.assetId }, reversible: false, dataClasses: ['C1'] }), execute: async (input, context) => requireFrontendSuccess(await invoke({ kind: 'command', command: { name: 'delete_asset', input, expectedRevisions: expectedRevision(context.hostContext?.scopeRevisions, ['assets']) } }, context)), concurrencyKey: (input) => `asset:${input.assetId}`, targetIds: (input) => ({ assetId: input.assetId }), dataClasses: () => ['C1'], summarize: (output) => `素材 ${String(output.assetId)} 已删除。`,
  })
  return [eraseToolDefinition(queryAssets), eraseToolDefinition(getAsset), eraseToolDefinition(listLibraries), eraseToolDefinition(listTags), eraseToolDefinition(selectAsset), eraseToolDefinition(setTags), eraseToolDefinition(addToLibrary), eraseToolDefinition(removeFromLibrary), eraseToolDefinition(deleteAsset)]
}
