import { CANVAS_NODE_TYPES, NODE_TOOL_TYPES } from '../domain/canvasNodes';
import {
  PANORAMA_MODEL_POLICY,
  PANORAMA_PROMPT_POLICY,
} from './panoramaPolicy';
import {
  CANVAS_IMAGE_CAPABILITY_IDS,
  type CanvasImageCapabilityDefinition,
} from './types';

const IMAGE_SOURCE = {
  mediaTypes: ['image'],
  minCount: 1,
  maxCount: 1,
  requireMaterializedMedia: true,
} as const;

const VERIFIED_MODEL_POLICY = {
  mode: 'verified-families',
  allowedCanonicalFamilies: [],
  requiredTags: [],
  providerCompatibility: 'verified-combinations-only',
  allowedProviderConfigurations: [],
  semanticRequirements: {},
} as const;

const PLANNED_AVAILABILITY = {
  releaseStage: 'draft',
  defaultEnabled: false,
  unavailableReasonKey: 'imageCapabilities.unavailable.planned',
} as const;

const PLANNED_IMPLEMENTATION = {
  status: 'planned',
  execution: null,
} as const;

export const builtInCanvasImageCapabilities: readonly CanvasImageCapabilityDefinition[] = [
  {
    id: CANVAS_IMAGE_CAPABILITY_IDS.panorama,
    titleKey: 'imageCapabilities.items.panorama.title',
    descriptionKey: 'imageCapabilities.items.panorama.description',
    group: 'generation',
    groupLabelKey: 'imageCapabilities.groups.generation',
    icon: 'panorama',
    order: 10,
    source: IMAGE_SOURCE,
    node: { kind: 'standard-generation', editor: 'standard' },
    implementation: {
      status: 'implemented',
      execution: {
        kind: 'canvas-node',
        nodeType: CANVAS_NODE_TYPES.panoramaGen,
      },
    },
    availability: {
      releaseStage: 'available',
      defaultEnabled: true,
      unavailableReasonKey: null,
    },
    modelPolicy: PANORAMA_MODEL_POLICY,
    promptPolicy: PANORAMA_PROMPT_POLICY,
    outputPolicy: {
      resultKind: 'panorama',
      count: { mode: 'single' },
      postProcess: 'validate-panorama',
      failureMode: 'single-result',
    },
  },
  {
    id: CANVAS_IMAGE_CAPABILITY_IDS.relight,
    titleKey: 'imageCapabilities.items.relight.title',
    descriptionKey: 'imageCapabilities.items.relight.description',
    group: 'editing',
    groupLabelKey: 'imageCapabilities.groups.editing',
    icon: 'relight',
    order: 20,
    source: IMAGE_SOURCE,
    node: { kind: 'special-generation', editor: 'relight' },
    implementation: PLANNED_IMPLEMENTATION,
    availability: PLANNED_AVAILABILITY,
    modelPolicy: VERIFIED_MODEL_POLICY,
    promptPolicy: {
      hiddenTemplateVersion: 'relight-v1-draft',
      fixedSemanticParams: {},
      visibleParameterKeys: ['lightingMode', 'lightDirection', 'brightness', 'lightColor'],
    },
    outputPolicy: {
      resultKind: 'image',
      count: { mode: 'single' },
      postProcess: 'none',
      failureMode: 'single-result',
    },
  },
  {
    id: CANVAS_IMAGE_CAPABILITY_IDS.multiAngle,
    titleKey: 'imageCapabilities.items.multiAngle.title',
    descriptionKey: 'imageCapabilities.items.multiAngle.description',
    group: 'structure',
    groupLabelKey: 'imageCapabilities.groups.structure',
    icon: 'multiAngle',
    order: 30,
    source: IMAGE_SOURCE,
    node: { kind: 'special-generation', editor: 'multiAngle' },
    implementation: PLANNED_IMPLEMENTATION,
    availability: PLANNED_AVAILABILITY,
    modelPolicy: VERIFIED_MODEL_POLICY,
    promptPolicy: {
      hiddenTemplateVersion: 'multi-angle-v1-draft',
      fixedSemanticParams: {},
      visibleParameterKeys: ['viewPreset', 'azimuth', 'elevation', 'shotSize', 'prompt'],
    },
    outputPolicy: {
      resultKind: 'image-group',
      count: {
        mode: 'parameter',
        parameterKey: 'viewCount',
        defaultCount: 4,
        minCount: 1,
        maxCount: 12,
      },
      postProcess: 'assemble-image-group',
      failureMode: 'atomic-results',
    },
  },
  {
    id: CANVAS_IMAGE_CAPABILITY_IDS.nineGrid,
    titleKey: 'imageCapabilities.items.nineGrid.title',
    descriptionKey: 'imageCapabilities.items.nineGrid.description',
    group: 'structure',
    groupLabelKey: 'imageCapabilities.groups.structure',
    icon: 'nineGrid',
    order: 40,
    source: IMAGE_SOURCE,
    node: { kind: 'standard-generation', editor: 'standard' },
    implementation: PLANNED_IMPLEMENTATION,
    availability: PLANNED_AVAILABILITY,
    modelPolicy: VERIFIED_MODEL_POLICY,
    promptPolicy: {
      hiddenTemplateVersion: 'nine-grid-v1-draft',
      fixedSemanticParams: { rows: 3, columns: 3 },
      visibleParameterKeys: ['prompt'],
    },
    outputPolicy: {
      resultKind: 'image-group',
      count: { mode: 'fixed', count: 9 },
      postProcess: 'assemble-image-group',
      failureMode: 'atomic-results',
    },
  },
  {
    id: CANVAS_IMAGE_CAPABILITY_IDS.upscale,
    titleKey: 'imageCapabilities.items.upscale.title',
    descriptionKey: 'imageCapabilities.items.upscale.description',
    group: 'enhancement',
    groupLabelKey: 'imageCapabilities.groups.enhancement',
    icon: 'upscale',
    order: 50,
    source: IMAGE_SOURCE,
    node: { kind: 'standard-generation', editor: 'standard' },
    implementation: PLANNED_IMPLEMENTATION,
    availability: PLANNED_AVAILABILITY,
    modelPolicy: VERIFIED_MODEL_POLICY,
    promptPolicy: {
      hiddenTemplateVersion: null,
      fixedSemanticParams: {},
      visibleParameterKeys: ['scale', 'fidelity'],
    },
    outputPolicy: {
      resultKind: 'image',
      count: { mode: 'single' },
      postProcess: 'none',
      failureMode: 'single-result',
    },
  },
  {
    id: CANVAS_IMAGE_CAPABILITY_IDS.portraitTexture,
    titleKey: 'imageCapabilities.items.portraitTexture.title',
    descriptionKey: 'imageCapabilities.items.portraitTexture.description',
    group: 'enhancement',
    groupLabelKey: 'imageCapabilities.groups.enhancement',
    icon: 'portraitTexture',
    order: 60,
    source: IMAGE_SOURCE,
    node: { kind: 'standard-generation', editor: 'standard' },
    implementation: PLANNED_IMPLEMENTATION,
    availability: PLANNED_AVAILABILITY,
    modelPolicy: VERIFIED_MODEL_POLICY,
    promptPolicy: {
      hiddenTemplateVersion: 'portrait-texture-v1-draft',
      fixedSemanticParams: {},
      visibleParameterKeys: ['strength', 'preset'],
    },
    outputPolicy: {
      resultKind: 'image',
      count: { mode: 'single' },
      postProcess: 'none',
      failureMode: 'single-result',
    },
  },
  {
    id: CANVAS_IMAGE_CAPABILITY_IDS.elementEdit,
    titleKey: 'imageCapabilities.items.elementEdit.title',
    descriptionKey: 'imageCapabilities.items.elementEdit.description',
    group: 'editing',
    groupLabelKey: 'imageCapabilities.groups.editing',
    icon: 'elementEdit',
    order: 70,
    source: IMAGE_SOURCE,
    node: { kind: 'special-generation', editor: 'mask' },
    implementation: PLANNED_IMPLEMENTATION,
    availability: PLANNED_AVAILABILITY,
    modelPolicy: VERIFIED_MODEL_POLICY,
    promptPolicy: {
      hiddenTemplateVersion: 'element-edit-v1-draft',
      fixedSemanticParams: {},
      visibleParameterKeys: ['prompt', 'mask'],
    },
    outputPolicy: {
      resultKind: 'image',
      count: { mode: 'single' },
      postProcess: 'none',
      failureMode: 'single-result',
    },
  },
  {
    id: CANVAS_IMAGE_CAPABILITY_IDS.layerSeparation,
    titleKey: 'imageCapabilities.items.layerSeparation.title',
    descriptionKey: 'imageCapabilities.items.layerSeparation.description',
    group: 'structure',
    groupLabelKey: 'imageCapabilities.groups.structure',
    icon: 'layerSeparation',
    order: 80,
    source: IMAGE_SOURCE,
    node: { kind: 'special-generation', editor: 'layers' },
    implementation: PLANNED_IMPLEMENTATION,
    availability: PLANNED_AVAILABILITY,
    modelPolicy: VERIFIED_MODEL_POLICY,
    promptPolicy: {
      hiddenTemplateVersion: 'layer-separation-v1-draft',
      fixedSemanticParams: {},
      visibleParameterKeys: ['layerCount'],
    },
    outputPolicy: {
      resultKind: 'layer-stack',
      count: {
        mode: 'parameter',
        parameterKey: 'layerCount',
        defaultCount: 4,
        minCount: 2,
        maxCount: 16,
      },
      postProcess: 'assemble-layer-stack',
      failureMode: 'atomic-results',
    },
  },
  {
    id: CANVAS_IMAGE_CAPABILITY_IDS.gridSplit,
    titleKey: 'imageCapabilities.items.gridSplit.title',
    descriptionKey: 'imageCapabilities.items.gridSplit.description',
    group: 'local',
    groupLabelKey: 'imageCapabilities.groups.local',
    icon: 'gridSplit',
    order: 90,
    source: IMAGE_SOURCE,
    node: { kind: 'local-tool', editor: 'gridSplit' },
    implementation: {
      status: 'implemented',
      execution: {
        kind: 'local-tool',
        toolType: NODE_TOOL_TYPES.splitStoryboard,
      },
    },
    availability: {
      releaseStage: 'available',
      defaultEnabled: true,
      unavailableReasonKey: null,
    },
    modelPolicy: { mode: 'not-applicable' },
    promptPolicy: {
      hiddenTemplateVersion: null,
      fixedSemanticParams: {},
      visibleParameterKeys: ['rows', 'columns', 'lineThickness'],
    },
    outputPolicy: {
      resultKind: 'image-group',
      count: {
        mode: 'parameter',
        parameterKey: 'cellCount',
        defaultCount: 9,
        minCount: 1,
        maxCount: 100,
      },
      postProcess: 'split-grid',
      failureMode: 'atomic-results',
    },
  },
];
