import { z } from 'zod'
import { applicationRefSchema } from '../../applicationCapabilities'
import { capabilityControl, defineApplicationCapability } from '../shared/defineApplicationCapability'
import { styleKitContentSchema } from '../../../videoEdit/styleKit'
const ref = <K extends string>(kind: K): z.ZodObject<Omit<typeof applicationRefSchema.shape, 'kind'> & { kind: z.ZodLiteral<K> }, z.core.$strict> => applicationRefSchema.extend({ kind: z.literal(kind) }).strict()
export const styleKitTargetSchema = z.object({ documentRef: ref('video_edit.document'), sequenceRef: ref('video_edit.sequence') }).strict()
const target = styleKitTargetSchema
const candidate = z.object({ name: z.string(), content: styleKitContentSchema, message: z.string() }).strict()
const common = { version: 1, domain: 'video_edit' as const, readOnly: true, risk: 'R0' as const, dataClasses: ['C1'] as ['C1'], permission: 'video_edit:read', idempotent: true, destructive: false, timeoutMs: 60000, supportsPreview: false, supportsUndo: false, requiredScopes: ['video_edit'] as ['video_edit'], producesRefs: [], resolveOperationWriteTargets: () => [], outputSchema: candidate, summarize: (value: z.infer<typeof candidate>) => value.message }
export const extractVideoEditWorkStyleCapability = defineApplicationCapability({ ...common, id: 'extract_video_edit_work_style', title: '从当前作品提取风格', description: '分析明确序列的文字/图形字体颜色、代码参数与常用入退时长和缓动，返回 name/content 风格候选，不写工程。先预览候选再通过通用 style_kit 集合创建，写 sequence.style_kit_id 绑定；可修改 rules 补气质/长期偏好。', aliases: ['沉淀风格', '从作品提取', 'style extraction'], acceptsRefs: ['video_edit.document', 'video_edit.sequence'], inputSchema: target.extend({ name: z.string().trim().min(1).max(200).default('作品风格') }).strict(), resolveConcurrencyKey: input => `style_extract:${input.documentRef.id}`, resolveOperationTargets: input => [input.documentRef, input.sequenceRef], control: capabilityControl('observe', ['video_edit.sequence'], { cancelable: true, revisionScopes: ['video_edit'] }) })
const reference = z.discriminatedUnion('kind', [z.object({ kind: z.literal('item'), itemRef: ref('video_edit.item'), timeUs: z.number().int().nonnegative().default(0) }).strict(), z.object({ kind: z.literal('asset'), assetRef: ref('asset') }).strict()])
export const extractVideoEditReferenceStyleCapability = defineApplicationCapability({ ...common, id: 'extract_video_edit_reference_style', title: '从参考图片提取风格配色', description: '选择剪辑图片/视频素材的指定源时间（timeUs 微秒）或资产库图片；缩图采样、中位切分后按面积/对比度分配背景、前景与强调，返回候选，不写工程或素材库。图片只提取配色，不断言字体气质；助手可通过正式媒体观察入口读图补 rules，再通用创建 style_kit 供用户预览确认。资产图片需要 assets:read 权限。', aliases: ['参考图风格', '提取配色', 'color palette'], acceptsRefs: ['video_edit.document', 'video_edit.sequence', 'video_edit.item', 'asset'], inputSchema: target.extend({ reference, name: z.string().trim().min(1).max(200).default('参考风格') }).strict(), resolveConcurrencyKey: input => `style_reference:${input.documentRef.id}`, resolveOperationTargets: input => [input.documentRef, input.sequenceRef, input.reference.kind === 'asset' ? input.reference.assetRef : input.reference.itemRef], control: capabilityControl('observe', ['video_edit.sequence'], { cancelable: true, revisionScopes: ['video_edit'] }) })
const sampleInput = target.extend({ styleRef: applicationRefSchema.extend({ kind: z.enum(['video_edit.style_kit', 'video_edit.style_preset']) }).strict(), sampleId: z.string().min(1).max(100), frame: z.number().int().nonnegative() }).strict()
const sampleOutput = z.object({ resultRef: ref('video_edit.document'), clipRefs: z.array(ref('video_edit.clip')), itemRefs: z.array(ref('video_edit.item')), definitionRefs: z.array(ref('video_edit.code_material')), versionRefs: z.array(ref('video_edit.code_version')), trackRefs: z.array(ref('video_edit.track')), styleRef: ref('video_edit.style_kit'), sequenceRef: ref('video_edit.sequence'), styleEffect: z.enum(['create', 'update']), verified: z.boolean(), message: z.string() }).strict()
export const insertVideoEditStyleSampleCapability = defineApplicationCapability({
  id: 'insert_video_edit_style_component', title: '插入风格组件', description: '先读风格实体 content.samples，用其 sampleId 将 v3 组件编译、试绘并放到明确序列播放头上方。组件、素材、工程风格快照和序列绑定一次撤销；若传本机预设会复制快照到工程，已有工程风格保持其身份。', version: 1, domain: 'video_edit', aliases: ['风格标题', '风格人名条', '样例组件'], readOnly: false, risk: 'R1', dataClasses: ['C1'], permission: 'video_edit:write', idempotent: false, destructive: false, timeoutMs: 60000, supportsPreview: false, supportsUndo: true, requiredScopes: ['video_edit'], acceptsRefs: ['video_edit.document', 'video_edit.sequence', 'video_edit.style_kit', 'video_edit.style_preset'], producesRefs: ['video_edit.clip', 'video_edit.item', 'video_edit.code_material', 'video_edit.code_version', 'video_edit.track', 'video_edit.style_kit'], inputSchema: sampleInput, outputSchema: sampleOutput,
  resolveConcurrencyKey: input => `video_edit:${input.documentRef.id}`, resolveOperationTargets: input => [input.documentRef, input.sequenceRef, input.styleRef], resolveOperationWriteTargets: input => [input.documentRef],
  control: capabilityControl('execute', ['video_edit.document'], { cancelable: true, revisionScopes: ['video_edit'], alsoImpacts: [{ effect: 'create', entityTypes: ['video_edit.clip', 'video_edit.item', 'video_edit.code_material', 'video_edit.code_version', 'video_edit.track', 'video_edit.style_kit'] }, { effect: 'update', entityTypes: ['video_edit.sequence', 'video_edit.style_kit'] }] }),
  verificationContract: { kind: 'effect_receipt', requireEffects: true, requireVerifiedEffects: true }, summarize: result => result.message,
  resolveObservedEffects: (_input, result) => [
    { effect: 'execute', entityTypes: ['video_edit.document'], propertyIds: [], targetRefs: [result.resultRef], count: 1, verified: result.verified, evidence: result.verified ? ['工程已保存并回读。'] : [] },
    ...([['video_edit.clip', result.clipRefs], ['video_edit.item', result.itemRefs], ['video_edit.code_material', result.definitionRefs], ['video_edit.code_version', result.versionRefs], ['video_edit.track', result.trackRefs]] as const).filter(([, refs]) => refs.length).map(([type, refs]) => ({ effect: 'create' as const, entityTypes: [type], propertyIds: [], targetRefs: [...refs], count: refs.length, verified: result.verified, evidence: result.verified ? ['新组件已从工程回读。'] : [] })),
    { effect: result.styleEffect, entityTypes: ['video_edit.style_kit'], propertyIds: result.styleEffect === 'update' ? ['video_edit.style_kit.content'] : [], targetRefs: [result.styleRef], count: 1, verified: result.verified, evidence: result.verified ? ['风格快照已从工程回读。'] : [] },
    { effect: 'update', entityTypes: ['video_edit.sequence'], propertyIds: ['video_edit.sequence.style_kit_id'], targetRefs: [result.sequenceRef], count: 1, verified: result.verified, evidence: result.verified ? ['序列风格绑定已回读。'] : [] },
  ],
})
export const VIDEO_EDIT_STYLE_KIT_CAPABILITIES = [extractVideoEditWorkStyleCapability, extractVideoEditReferenceStyleCapability, insertVideoEditStyleSampleCapability]
