import { z } from 'zod'

import type { ApplicationCapabilityDefinition } from '../applicationCapabilities'
import {
  capabilityOutputSchema,
  defineApplicationCapability,
} from './defineApplicationCapability'

const queryAssets = defineApplicationCapability({
  id: 'query_assets',
  version: 1,
  title: '查询素材库',
  description: '按媒体类型、标签、集合和关键词分页查询素材摘要，不返回本地文件路径。',
  domain: 'assets',
  aliases: ['查找素材', '素材库', '搜索图片', 'search assets'],
  readOnly: true,
  risk: 'R0',
  dataClasses: ['C1'],
  permission: 'assets:read',
  idempotent: true,
  destructive: false,
  timeoutMs: 8_000,
  supportsPreview: false,
  supportsUndo: false,
  requiredScopes: [],
  producesRefs: ['asset'],
  inputSchema: z.object({
    mediaType: z.enum(['image', 'video', 'audio']).optional(),
    libraryId: z.string().min(1).optional(),
    tag: z.string().min(1).optional(),
    keyword: z.string().max(200).optional(),
    page: z.number().int().min(1).max(1_000).default(1),
    pageSize: z.number().int().min(1).max(50).default(20),
    sort: z.enum(['created', 'recent']).default('created'),
  }).strict(),
  outputSchema: capabilityOutputSchema({
    items: z.array(z.record(z.string(), z.unknown())),
    total: z.number(),
    page: z.number(),
    pageSize: z.number(),
  }),
  concurrencyKey: 'assets_query',
  resolveTargetIds: (input) => ({
    keyword: input.keyword ?? '',
    libraryId: input.libraryId ?? '',
  }),
  summarize: (output) => `素材库返回 ${output.items.length} 项。`,
})

const getAsset = defineApplicationCapability({
  id: 'get_asset',
  version: 1,
  title: '读取素材详情',
  description: '按稳定素材引用读取元数据、标签和集合信息。',
  domain: 'assets',
  aliases: ['素材详情', '这张素材', '读取图片素材', 'get asset'],
  readOnly: true,
  risk: 'R0',
  dataClasses: ['C1'],
  permission: 'assets:read',
  idempotent: true,
  destructive: false,
  timeoutMs: 5_000,
  supportsPreview: false,
  supportsUndo: false,
  requiredScopes: [],
  acceptsRefs: ['asset'],
  producesRefs: ['asset'],
  inputSchema: z.object({ assetId: z.string().min(1) }).strict(),
  outputSchema: capabilityOutputSchema({
    asset: z.record(z.string(), z.unknown()),
  }),
  concurrencyKey: 'asset',
  resolveConcurrencyKey: (input) => `asset:${input.assetId}`,
  resolveTargetIds: (input) => ({ assetId: input.assetId }),
  summarize: (output) => `已读取素材 ${String(output.asset.id ?? '')}。`,
})

const listAssetLibraries = defineApplicationCapability({
  id: 'list_asset_libraries',
  version: 1,
  title: '列出素材集合',
  description: '列出素材库中的集合摘要。',
  domain: 'assets',
  aliases: ['素材集合', '素材分类', 'asset libraries'],
  readOnly: true,
  risk: 'R0',
  dataClasses: ['C0'],
  permission: 'assets:read',
  idempotent: true,
  destructive: false,
  timeoutMs: 5_000,
  supportsPreview: false,
  supportsUndo: false,
  requiredScopes: [],
  producesRefs: ['asset.library'],
  inputSchema: z.object({}).strict(),
  outputSchema: capabilityOutputSchema({
    libraries: z.array(z.record(z.string(), z.unknown())),
  }),
  concurrencyKey: 'asset_libraries',
  summarize: (output) => `素材集合返回 ${output.libraries.length} 项。`,
})

const listAssetTags = defineApplicationCapability({
  id: 'list_asset_tags',
  version: 1,
  title: '列出素材标签',
  description: '列出已有素材标签，供筛选或标记使用。',
  domain: 'assets',
  aliases: ['素材标签', '标签列表', 'asset tags'],
  readOnly: true,
  risk: 'R0',
  dataClasses: ['C0'],
  permission: 'assets:read',
  idempotent: true,
  destructive: false,
  timeoutMs: 5_000,
  supportsPreview: false,
  supportsUndo: false,
  requiredScopes: [],
  inputSchema: z.object({}).strict(),
  outputSchema: capabilityOutputSchema({ tags: z.array(z.string()) }),
  concurrencyKey: 'asset_tags',
  summarize: (output) => `素材标签返回 ${output.tags.length} 项。`,
})

const selectAsset = defineApplicationCapability({
  id: 'select_asset',
  version: 1,
  title: '选择素材',
  description: '在素材界面选择或清除一个明确素材。',
  domain: 'assets',
  aliases: ['选中素材', '定位素材', 'select asset'],
  readOnly: false,
  risk: 'R0',
  dataClasses: ['C1'],
  permission: 'assets:selection',
  idempotent: true,
  destructive: false,
  timeoutMs: 5_000,
  supportsPreview: false,
  supportsUndo: false,
  requiredScopes: ['assets'],
  acceptsRefs: ['asset'],
  producesRefs: ['asset'],
  inputSchema: z.object({ assetId: z.string().min(1).nullable() }).strict(),
  outputSchema: capabilityOutputSchema({ assetId: z.string().nullable() }),
  concurrencyKey: 'asset_selection',
  resolveTargetIds: (input) => ({ assetId: input.assetId ?? '' }),
  summarize: (output) => `当前选中素材：${output.assetId ?? '无'}。`,
})

const setAssetTags = defineApplicationCapability({
  id: 'set_asset_tags',
  version: 1,
  title: '设置素材标签',
  description: '覆盖明确素材的标签集合，不修改原始文件。',
  domain: 'assets',
  aliases: ['修改素材标签', '标记素材', 'set asset tags'],
  readOnly: false,
  risk: 'R1',
  dataClasses: ['C1'],
  permission: 'assets:write',
  idempotent: true,
  destructive: false,
  timeoutMs: 8_000,
  supportsPreview: false,
  supportsUndo: false,
  requiredScopes: ['assets'],
  acceptsRefs: ['asset'],
  producesRefs: ['asset'],
  inputSchema: z.object({
    assetId: z.string().min(1),
    tags: z.array(z.string().trim().min(1).max(80)).max(32),
  }).strict(),
  outputSchema: capabilityOutputSchema({
    assetId: z.string(),
    tags: z.array(z.string()),
  }),
  concurrencyKey: 'asset',
  resolveConcurrencyKey: (input) => `asset:${input.assetId}`,
  resolveTargetIds: (input) => ({ assetId: input.assetId }),
  summarize: (output) => `已更新素材 ${output.assetId} 的标签。`,
})

function defineAssetLibraryMembershipCapability(
  id: 'add_asset_to_library' | 'remove_asset_from_library',
  status: 'added' | 'removed'
): ApplicationCapabilityDefinition {
  const adding = status === 'added'
  return defineApplicationCapability({
    id,
    version: 1,
    title: adding ? '添加素材到集合' : '从集合移除素材',
    description: adding
      ? '把明确素材加入指定集合。'
      : '从指定集合移除明确素材，不删除素材本身。',
    domain: 'assets',
    aliases: adding ? ['加入素材集合', 'add asset to library'] : ['移出素材集合', 'remove asset from library'],
    readOnly: false,
    risk: 'R1',
    dataClasses: ['C1'],
    permission: 'assets:write',
    idempotent: true,
    destructive: false,
    timeoutMs: 8_000,
    supportsPreview: false,
    supportsUndo: false,
    requiredScopes: ['assets'],
    acceptsRefs: ['asset', 'asset.library'],
    producesRefs: ['asset', 'asset.library'],
    inputSchema: z.object({
      libraryId: z.string().min(1),
      assetId: z.string().min(1),
    }).strict(),
    outputSchema: capabilityOutputSchema({
      libraryId: z.string(),
      assetId: z.string(),
      status: z.literal(status),
    }),
    concurrencyKey: 'asset_library',
    resolveConcurrencyKey: (input) => `library:${input.libraryId}`,
    resolveTargetIds: (input) => ({
      libraryId: input.libraryId,
      assetId: input.assetId,
    }),
    summarize: (output) => adding
      ? `素材 ${String(output.assetId)} 已加入集合。`
      : `素材 ${String(output.assetId)} 已从集合移除。`,
  })
}

const deleteAsset = defineApplicationCapability({
  id: 'delete_asset',
  version: 1,
  title: '删除素材',
  description: '永久删除明确素材记录及其受控文件引用。',
  domain: 'assets',
  aliases: ['永久删除素材', 'delete asset'],
  readOnly: false,
  risk: 'R3',
  dataClasses: ['C1'],
  permission: 'assets:delete',
  idempotent: true,
  destructive: true,
  timeoutMs: 10_000,
  supportsPreview: true,
  supportsUndo: false,
  requiredScopes: ['assets'],
  acceptsRefs: ['asset'],
  inputSchema: z.object({ assetId: z.string().min(1) }).strict(),
  outputSchema: capabilityOutputSchema({
    assetId: z.string(),
    status: z.literal('deleted'),
  }),
  concurrencyKey: 'asset',
  resolveConcurrencyKey: (input) => `asset:${input.assetId}`,
  resolveTargetIds: (input) => ({ assetId: input.assetId }),
  preview: (input) => ({
    title: '删除素材',
    summary: `永久删除素材 ${input.assetId}；此操作不可撤销。`,
    targetIds: { assetId: input.assetId },
    reversible: false,
    dataClasses: ['C1'],
  }),
  summarize: (output) => `素材 ${output.assetId} 已删除。`,
})

export const ASSET_APPLICATION_CAPABILITIES: ApplicationCapabilityDefinition[] = [
  queryAssets,
  getAsset,
  listAssetLibraries,
  listAssetTags,
  selectAsset,
  setAssetTags,
  defineAssetLibraryMembershipCapability('add_asset_to_library', 'added'),
  defineAssetLibraryMembershipCapability('remove_asset_from_library', 'removed'),
  deleteAsset,
]
