import { z } from 'zod'

import type { ApplicationCapabilityDefinition } from '../applicationCapabilities'
import {
  capabilityOutputSchema,
  defineApplicationCapability,
} from './defineApplicationCapability'

function cameraTarget(projectId: string, extra: Record<string, string> = {}): Record<string, string> {
  return { projectId, ...extra }
}

const listProjects = defineApplicationCapability({
  id: 'list_camera_stage_projects',
  version: 1,
  title: '列出 3D 运镜工程',
  description: '列出 3D 镜头参考工程摘要。',
  domain: 'camera_stage',
  aliases: ['3D 工程', '运镜工程', 'camera stage projects'],
  readOnly: true,
  risk: 'R0',
  dataClasses: ['C1'],
  permission: 'camera_stage:read',
  idempotent: true,
  destructive: false,
  timeoutMs: 8_000,
  supportsPreview: false,
  supportsUndo: false,
  requiredScopes: [],
  producesRefs: ['camera_stage.project'],
  inputSchema: z.object({}).strict(),
  outputSchema: capabilityOutputSchema({
    projects: z.array(z.record(z.string(), z.unknown())),
  }),
  concurrencyKey: 'camera_stage_catalog',
  summarize: (output) => `3D 运镜工程目录返回 ${output.projects.length} 项。`,
})

const getProject = defineApplicationCapability({
  id: 'get_camera_stage_project',
  version: 1,
  title: '读取 3D 运镜工程',
  description: '按工程引用读取 3D 场景摘要和有限大小的序列化数据。',
  domain: 'camera_stage',
  aliases: ['3D 工程详情', 'get camera stage project'],
  readOnly: true,
  risk: 'R0',
  dataClasses: ['C1'],
  permission: 'camera_stage:read',
  idempotent: true,
  destructive: false,
  timeoutMs: 8_000,
  supportsPreview: false,
  supportsUndo: false,
  requiredScopes: [],
  acceptsRefs: ['camera_stage.project'],
  producesRefs: ['camera_stage.project', 'camera_stage.object', 'camera_stage.shot'],
  inputSchema: z.object({ projectId: z.string().min(1) }).strict(),
  outputSchema: capabilityOutputSchema({
    project: z.record(z.string(), z.unknown()),
  }),
  concurrencyKey: 'camera_stage_project',
  resolveConcurrencyKey: (input) => `camera_stage_project:${input.projectId}`,
  resolveTargetIds: (input) => cameraTarget(input.projectId),
  summarize: (output) => `已读取 3D 运镜工程 ${String(output.project.id ?? '')}。`,
})

const openProject = defineApplicationCapability({
  id: 'open_camera_stage_project',
  version: 1,
  title: '打开 3D 运镜工程',
  description: '打开明确 3D 工程并进入工具箱编辑器。',
  domain: 'camera_stage',
  aliases: ['进入 3D 工程', 'open camera stage project'],
  readOnly: false,
  risk: 'R1',
  dataClasses: ['C1'],
  permission: 'camera_stage:open',
  idempotent: true,
  destructive: false,
  timeoutMs: 15_000,
  supportsPreview: false,
  supportsUndo: false,
  requiredScopes: ['toolbox'],
  acceptsRefs: ['camera_stage.project'],
  producesRefs: ['camera_stage.project', 'application.surface'],
  inputSchema: z.object({ projectId: z.string().min(1) }).strict(),
  outputSchema: capabilityOutputSchema({
    projectId: z.string(),
    name: z.string().optional(),
    objectCount: z.number(),
    shotCount: z.number(),
  }),
  concurrencyKey: 'camera_stage_open',
  resolveTargetIds: (input) => cameraTarget(input.projectId),
  summarize: (output) => `已打开 3D 运镜工程 ${output.projectId}。`,
})

const createProject = defineApplicationCapability({
  id: 'create_camera_stage_project',
  version: 1,
  title: '新建 3D 运镜工程',
  description: '创建 3D 运镜工程并进入编辑器。',
  domain: 'camera_stage',
  aliases: ['创建 3D 工程', 'new camera stage project'],
  readOnly: false,
  risk: 'R1',
  dataClasses: ['C1'],
  permission: 'camera_stage:write',
  idempotent: false,
  destructive: false,
  timeoutMs: 15_000,
  supportsPreview: false,
  supportsUndo: false,
  requiredScopes: ['toolbox'],
  producesRefs: ['camera_stage.project', 'application.surface'],
  inputSchema: z.object({
    name: z.string().trim().min(1).max(120),
    mode: z.enum(['simple', 'pro']).default('simple'),
  }).strict(),
  outputSchema: capabilityOutputSchema({
    projectId: z.string(),
    name: z.string(),
    mode: z.enum(['simple', 'pro']),
  }),
  concurrencyKey: 'camera_stage_project',
  resolveTargetIds: (input) => ({ name: input.name }),
  summarize: (output) => `已创建 3D 运镜工程 ${output.projectId}。`,
})

const renameProject = defineApplicationCapability({
  id: 'rename_camera_stage_project',
  version: 1,
  title: '重命名 3D 运镜工程',
  description: '重命名明确的 3D 运镜工程。',
  domain: 'camera_stage',
  aliases: ['修改 3D 工程名称', 'rename camera project'],
  readOnly: false,
  risk: 'R1',
  dataClasses: ['C1'],
  permission: 'camera_stage:write',
  idempotent: true,
  destructive: false,
  timeoutMs: 10_000,
  supportsPreview: false,
  supportsUndo: false,
  requiredScopes: ['toolbox'],
  acceptsRefs: ['camera_stage.project'],
  producesRefs: ['camera_stage.project'],
  inputSchema: z.object({
    projectId: z.string().min(1),
    name: z.string().trim().min(1).max(120),
  }).strict(),
  outputSchema: capabilityOutputSchema({
    projectId: z.string(),
    name: z.string(),
  }),
  concurrencyKey: 'camera_stage_project',
  resolveConcurrencyKey: (input) => `camera_stage_project:${input.projectId}`,
  resolveTargetIds: (input) => cameraTarget(input.projectId),
  summarize: (output) => `已重命名 3D 运镜工程 ${output.projectId}。`,
})

const deleteProject = defineApplicationCapability({
  id: 'delete_camera_stage_project',
  version: 1,
  title: '删除 3D 运镜工程',
  description: '永久删除明确的 3D 运镜工程及其场景数据。',
  domain: 'camera_stage',
  aliases: ['永久删除 3D 工程', 'delete camera project'],
  readOnly: false,
  risk: 'R3',
  dataClasses: ['C1'],
  permission: 'camera_stage:delete',
  idempotent: true,
  destructive: true,
  timeoutMs: 15_000,
  supportsPreview: true,
  supportsUndo: false,
  requiredScopes: ['toolbox'],
  acceptsRefs: ['camera_stage.project'],
  inputSchema: z.object({ projectId: z.string().min(1) }).strict(),
  outputSchema: capabilityOutputSchema({
    projectId: z.string(),
    status: z.literal('deleted'),
  }),
  concurrencyKey: 'camera_stage_project',
  resolveConcurrencyKey: (input) => `camera_stage_project:${input.projectId}`,
  resolveTargetIds: (input) => cameraTarget(input.projectId),
  preview: (input) => ({
    title: '删除 3D 运镜工程',
    summary: `永久删除工程 ${input.projectId}；此操作不可撤销。`,
    targetIds: cameraTarget(input.projectId),
    reversible: false,
    dataClasses: ['C1'],
  }),
  summarize: (output) => `3D 运镜工程 ${output.projectId} 已删除。`,
})

const objectTypeSchema = z.enum(['primitive', 'character', 'camera'])
const primitiveKindSchema = z.enum(['box', 'sphere', 'cylinder', 'cone', 'pyramid', 'torus'])

const addObject = defineApplicationCapability({
  id: 'add_camera_stage_object',
  version: 1,
  title: '添加 3D 场景对象',
  description: '按对象类型和几何预设添加 3D 场景对象。',
  domain: 'camera_stage',
  aliases: ['添加 3D 物体', 'add camera object'],
  readOnly: false,
  risk: 'R1',
  dataClasses: ['C1'],
  permission: 'camera_stage:write',
  idempotent: false,
  destructive: false,
  timeoutMs: 10_000,
  supportsPreview: false,
  supportsUndo: true,
  requiredScopes: ['toolbox'],
  acceptsRefs: ['camera_stage.project'],
  producesRefs: ['camera_stage.object'],
  inputSchema: z.object({
    projectId: z.string().min(1),
    objectType: objectTypeSchema,
    primitiveKind: primitiveKindSchema.optional(),
  }).strict(),
  outputSchema: capabilityOutputSchema({
    projectId: z.string(),
    objectId: z.string(),
    objectType: z.string(),
  }),
  concurrencyKey: 'camera_stage',
  resolveConcurrencyKey: (input) => `camera_stage:${input.projectId}`,
  resolveTargetIds: (input) => cameraTarget(input.projectId, { objectType: input.objectType }),
  summarize: (output) => `已添加 3D 对象 ${output.objectId}。`,
})

const duplicateObject = defineApplicationCapability({
  id: 'duplicate_camera_stage_object',
  version: 1,
  title: '复制 3D 场景对象',
  description: '复制明确的 3D 场景对象并保存为新对象。',
  domain: 'camera_stage',
  aliases: ['复制 3D 物体', 'duplicate camera object'],
  readOnly: false,
  risk: 'R1',
  dataClasses: ['C1'],
  permission: 'camera_stage:write',
  idempotent: false,
  destructive: false,
  timeoutMs: 10_000,
  supportsPreview: false,
  supportsUndo: true,
  requiredScopes: ['toolbox'],
  acceptsRefs: ['camera_stage.project', 'camera_stage.object'],
  producesRefs: ['camera_stage.object'],
  inputSchema: z.object({
    projectId: z.string().min(1),
    objectId: z.string().min(1),
  }).strict(),
  outputSchema: capabilityOutputSchema({
    projectId: z.string(),
    objectId: z.string(),
    duplicatedFromObjectId: z.string(),
  }),
  concurrencyKey: 'camera_stage',
  resolveConcurrencyKey: (input) => `camera_stage:${input.projectId}`,
  resolveTargetIds: (input) => cameraTarget(input.projectId, { objectId: input.objectId }),
  summarize: (output) => `已复制 3D 对象 ${output.duplicatedFromObjectId}，新对象为 ${output.objectId}。`,
})

const deleteObject = defineApplicationCapability({
  id: 'delete_camera_stage_object',
  version: 1,
  title: '删除 3D 场景对象',
  description: '永久删除明确的 3D 场景对象。',
  domain: 'camera_stage',
  aliases: ['删除 3D 物体', 'delete camera object'],
  readOnly: false,
  risk: 'R3',
  dataClasses: ['C1'],
  permission: 'camera_stage:delete',
  idempotent: true,
  destructive: true,
  timeoutMs: 10_000,
  supportsPreview: true,
  supportsUndo: false,
  requiredScopes: ['toolbox'],
  acceptsRefs: ['camera_stage.project', 'camera_stage.object'],
  inputSchema: z.object({
    projectId: z.string().min(1),
    objectId: z.string().min(1),
  }).strict(),
  outputSchema: capabilityOutputSchema({
    projectId: z.string(),
    objectId: z.string(),
    status: z.literal('deleted'),
  }),
  concurrencyKey: 'camera_stage',
  resolveConcurrencyKey: (input) => `camera_stage:${input.projectId}:${input.objectId}`,
  resolveTargetIds: (input) => cameraTarget(input.projectId, { objectId: input.objectId }),
  preview: (input) => ({
    title: '删除 3D 场景对象',
    summary: `删除对象 ${input.objectId}；此操作不可撤销。`,
    targetIds: cameraTarget(input.projectId, { objectId: input.objectId }),
    reversible: false,
    dataClasses: ['C1'],
  }),
  summarize: (output) => `3D 对象 ${output.objectId} 已删除。`,
})

const updateObject = defineApplicationCapability({
  id: 'update_camera_stage_object',
  version: 1,
  title: '更新 3D 场景对象',
  description: '按稳定对象引用更新名称、可见性、变换或类型专属参数。',
  domain: 'camera_stage',
  aliases: ['修改 3D 物体', 'update camera object'],
  readOnly: false,
  risk: 'R1',
  dataClasses: ['C1'],
  permission: 'camera_stage:write',
  idempotent: true,
  destructive: false,
  timeoutMs: 10_000,
  supportsPreview: false,
  supportsUndo: true,
  requiredScopes: ['toolbox'],
  acceptsRefs: ['camera_stage.project', 'camera_stage.object'],
  producesRefs: ['camera_stage.object'],
  inputSchema: z.object({
    projectId: z.string().min(1),
    objectId: z.string().min(1),
    patch: z.record(z.string(), z.unknown()),
  }).strict(),
  outputSchema: capabilityOutputSchema({
    projectId: z.string(),
    objectId: z.string(),
    updatedKeys: z.array(z.string()),
  }),
  concurrencyKey: 'camera_stage',
  resolveConcurrencyKey: (input) => `camera_stage:${input.projectId}:${input.objectId}`,
  resolveTargetIds: (input) => cameraTarget(input.projectId, { objectId: input.objectId }),
  summarize: (output) => `已更新 3D 对象 ${output.objectId}。`,
})

const addShot = defineApplicationCapability({
  id: 'add_camera_stage_shot',
  version: 1,
  title: '添加 3D 镜头卡',
  description: '在当前 3D 工程捕获一张镜头卡。',
  domain: 'camera_stage',
  aliases: ['添加镜头卡', 'add camera shot'],
  readOnly: false,
  risk: 'R1',
  dataClasses: ['C1'],
  permission: 'camera_stage:write',
  idempotent: false,
  destructive: false,
  timeoutMs: 10_000,
  supportsPreview: false,
  supportsUndo: true,
  requiredScopes: ['toolbox'],
  acceptsRefs: ['camera_stage.project', 'camera_stage.object'],
  producesRefs: ['camera_stage.shot'],
  inputSchema: z.object({
    projectId: z.string().min(1),
    name: z.string().trim().min(1).max(120),
    cameraId: z.string().min(1).nullable().default(null),
  }).strict(),
  outputSchema: capabilityOutputSchema({
    projectId: z.string(),
    shotId: z.string(),
    name: z.string(),
  }),
  concurrencyKey: 'camera_stage_shots',
  resolveConcurrencyKey: (input) => `camera_stage:${input.projectId}:shots`,
  resolveTargetIds: (input) => cameraTarget(input.projectId, { name: input.name }),
  summarize: (output) => `已添加镜头卡 ${output.shotId}。`,
})

const updateShot = defineApplicationCapability({
  id: 'update_camera_stage_shot',
  version: 1,
  title: '更新 3D 镜头卡',
  description: '按稳定镜头引用修改名称、停留、过渡和机位。',
  domain: 'camera_stage',
  aliases: ['修改镜头卡', 'update camera shot'],
  readOnly: false,
  risk: 'R1',
  dataClasses: ['C1'],
  permission: 'camera_stage:write',
  idempotent: true,
  destructive: false,
  timeoutMs: 10_000,
  supportsPreview: false,
  supportsUndo: true,
  requiredScopes: ['toolbox'],
  acceptsRefs: ['camera_stage.project', 'camera_stage.shot'],
  producesRefs: ['camera_stage.shot'],
  inputSchema: z.object({
    projectId: z.string().min(1),
    shotId: z.string().min(1),
    patch: z.object({
      name: z.string().trim().min(1).max(120).optional(),
      hold: z.number().min(0).max(3_600).optional(),
      transitionDuration: z.number().min(0).max(3_600).optional(),
      continuity: z.enum(['stop', 'smooth']).optional(),
      cameraId: z.string().min(1).nullable().optional(),
    }).strict(),
  }).strict(),
  outputSchema: capabilityOutputSchema({
    projectId: z.string(),
    shotId: z.string(),
    status: z.literal('updated'),
  }),
  concurrencyKey: 'camera_stage_shot',
  resolveConcurrencyKey: (input) => `camera_stage:${input.projectId}:shot:${input.shotId}`,
  resolveTargetIds: (input) => cameraTarget(input.projectId, { shotId: input.shotId }),
  summarize: (output) => `已更新镜头卡 ${output.shotId}。`,
})

export const CAMERA_STAGE_APPLICATION_CAPABILITIES: ApplicationCapabilityDefinition[] = [
  listProjects,
  getProject,
  openProject,
  createProject,
  renameProject,
  deleteProject,
  addObject,
  duplicateObject,
  deleteObject,
  updateObject,
  addShot,
  updateShot,
]
