import { z } from 'zod'

import { ASSISTANT_CANVAS_IMAGE_CAPABILITY_IDS } from '../../canvas/imageCapabilityIds'
import {
  applicationRefSchema,
  type ApplicationCapabilityDefinition,
} from '../applicationCapabilities'
import {
  capabilityControl,
  capabilityOutputSchema,
  defineApplicationCapability,
} from './defineApplicationCapability'

export const canvasNodePlacementSchema = z.discriminatedUnion('mode', [
  z.object({ mode: z.literal('viewport_center') }).strict(),
  z.object({
    mode: z.literal('absolute'),
    x: z.number().finite(),
    y: z.number().finite(),
  }).strict(),
  z.object({
    mode: z.literal('right_of_node'),
    anchorNodeId: z.string().min(1),
  }).strict(),
])
export type CanvasNodePlacement = z.infer<typeof canvasNodePlacementSchema>

function target(projectId: string, extra: Record<string, string> = {}): Record<string, string> {
  return { projectId, ...extra }
}

const addCanvasNode = defineApplicationCapability({
  id: 'add_canvas_node',
  version: 1,
  title: '添加画布节点',
  description: '在明确项目中按确定性布局添加已通过节点结构校验的节点。',
  domain: 'canvas',
  aliases: ['新建画布节点', 'add canvas node'],
  readOnly: false,
  risk: 'R1',
  dataClasses: ['C1'],
  permission: 'canvas:write',
  idempotent: true,
  destructive: false,
  timeoutMs: 8_000,
  supportsPreview: false,
  supportsUndo: true,
  requiredScopes: ['canvas'],
  prerequisites: [
    'nodeType 必须来自 search_canvas_node_types，且应先用 get_canvas_node_schema 校验数据和端口。',
  ],
  acceptsRefs: ['canvas.project', 'canvas.node_type'],
  producesRefs: ['canvas.node'],
  executionPrerequisites: ['get_canvas_node_schema'],
  inputSchema: z.object({
    projectId: z.string().min(1),
    nodeType: z.string().min(1),
    placement: canvasNodePlacementSchema,
    data: z.record(z.string(), z.unknown()).optional(),
  }).strict(),
  outputSchema: capabilityOutputSchema({
    projectId: z.string(),
    nodeId: z.string(),
    nodeType: z.string(),
    undoRef: z.string(),
  }),
  concurrencyKey: 'canvas',
  resolveConcurrencyKey: (input) => `canvas:${input.projectId}`,
  resolveTargetIds: (input) => target(input.projectId, { nodeType: input.nodeType }),
  summarize: (output) => `已在项目 ${output.projectId} 添加节点 ${output.nodeId}。`,
  createUndo: (output) => ({ kind: 'canvas_history', token: output.undoRef }),
  control: { execution: { mode: 'immediate', cancelable: false, resultState: 'completed' }, impacts: [{
    effect: 'create', entityTypes: ['canvas.node'], propertyIds: [], revisionScopes: ['canvas'], verificationRequired: true,
  }] },
  resolveObservedEffects: (_input, output) => [{
    effect: 'create', entityTypes: ['canvas.node'], propertyIds: [],
    targetRefs: [{ kind: 'canvas.node', id: output.nodeId }], count: 1, verified: false,
    evidence: [`node:${output.nodeId}`],
  }],
})

const applyCanvasImageCapability = defineApplicationCapability({
  id: 'apply_canvas_image_capability',
  version: 1,
  title: '应用画布图片能力',
  description: '对明确的图片来源节点应用已登记的画布图片能力，原子创建受控节点和连线。',
  domain: 'canvas',
  aliases: [
    '使用图片工具', '应用图片能力', 'apply canvas image capability',
    '高清放大', '图片超分', '图片打光 重打光', '暗光增强', '智能扩图',
    '商品摄影', '照片修复', '背景移除 移除背景', '多角度视图 调整镜头角度',
    '九宫格', '人像质感', '局部重绘', '图层拆分', '全景图',
    'upscale relight outpaint remove background background removal multi-angle',
    '移除这张图片的背景', '调整这张图的镜头角度',
  ],
  readOnly: false,
  risk: 'R1',
  dataClasses: ['C1'],
  permission: 'canvas:write',
  idempotent: false,
  destructive: false,
  timeoutMs: 12_000,
  supportsPreview: false,
  supportsUndo: true,
  requiredScopes: ['canvas'],
  prerequisites: ['sourceNodeId 必须引用当前项目中已有、且能输出已落地图片的节点。'],
  acceptsRefs: ['canvas.project', 'canvas.node'],
  producesRefs: ['canvas.node', 'canvas.edge'],
  inputSchema: z.object({
    projectId: z.string().min(1),
    sourceNodeId: z.string().min(1),
    capabilityId: z.enum(ASSISTANT_CANVAS_IMAGE_CAPABILITY_IDS),
  }).strict(),
  outputSchema: capabilityOutputSchema({
    projectId: z.string(),
    kind: z.literal('canvas-node'),
    capabilityId: z.enum(ASSISTANT_CANVAS_IMAGE_CAPABILITY_IDS),
    sourceNodeId: z.string(),
    nodeId: z.string(),
    edgeId: z.string(),
    undoRef: z.string(),
  }),
  concurrencyKey: 'canvas',
  resolveConcurrencyKey: (input) => `canvas:${input.projectId}`,
  resolveTargetIds: (input) => target(input.projectId, {
    sourceNodeId: input.sourceNodeId,
    capabilityId: input.capabilityId,
  }),
  summarize: (output) => `已应用图片能力 ${output.capabilityId}，创建节点 ${output.nodeId}。`,
  createUndo: (output) => ({ kind: 'canvas_history', token: output.undoRef }),
  control: {
    execution: { mode: 'immediate', cancelable: false, resultState: 'completed' },
    impacts: [
      { effect: 'create', entityTypes: ['canvas.node'], propertyIds: [], revisionScopes: ['canvas'], verificationRequired: true },
      { effect: 'create', entityTypes: ['canvas.edge'], propertyIds: [], revisionScopes: ['canvas'], verificationRequired: true },
      { effect: 'update', entityTypes: ['canvas.project'], propertyIds: ['canvas.project.selected_node'], revisionScopes: ['canvas'], verificationRequired: false },
    ],
  },
  successEvidence: ['返回实际创建的节点、连线与单次事务撤销引用。'],
  failureRecovery: [
    '先用 get_canvas_project / get_canvas_node 确认 sourceNodeId 已产出已落地图片；capabilityId 只能从本能力输入 schema 的枚举中选择。',
  ],
  resolveObservedEffects: (_input, output) => [
    {
      effect: 'create', entityTypes: ['canvas.node'], propertyIds: [],
      targetRefs: [{ kind: 'canvas.node', id: output.nodeId }], count: 1, verified: false,
      evidence: [`node:${output.nodeId}`],
    },
    {
      effect: 'create', entityTypes: ['canvas.edge'], propertyIds: [],
      targetRefs: [{ kind: 'canvas.edge', id: output.edgeId }], count: 1, verified: false,
      evidence: [`edge:${output.edgeId}`],
    },
    {
      effect: 'update', entityTypes: ['canvas.project'], propertyIds: ['canvas.project.selected_node'],
      targetRefs: [{ kind: 'canvas.project', id: output.projectId }], count: 1, verified: false,
      evidence: [`selected-node:${output.nodeId}`],
    },
  ],
})

const addAssetToCanvas = defineApplicationCapability({
  id: 'add_asset_to_canvas',
  version: 1,
  title: '把素材放入画布',
  description: '按稳定素材引用将素材作为受控输入节点放入明确画布项目。',
  domain: 'canvas',
  aliases: ['素材添加到画布', 'add asset to canvas'],
  readOnly: false,
  control: capabilityControl('create', ['canvas.node'], { revisionScopes: ['canvas'] }),
  risk: 'R1',
  dataClasses: ['C1'],
  permission: 'canvas:write',
  idempotent: true,
  destructive: false,
  timeoutMs: 12_000,
  supportsPreview: false,
  supportsUndo: true,
  requiredScopes: ['canvas', 'assets'],
  acceptsRefs: ['canvas.project', 'canvas.node', 'asset'],
  producesRefs: ['canvas.node', 'asset'],
  inputSchema: z.object({
    projectId: z.string().min(1),
    assetId: z.string().min(1),
    placement: canvasNodePlacementSchema,
  }).strict(),
  outputSchema: capabilityOutputSchema({
    projectId: z.string(),
    assetId: z.string(),
    mediaType: z.enum(['image', 'video', 'audio']),
    nodeId: z.string(),
    nodeType: z.string(),
    undoRef: z.string(),
  }),
  concurrencyKey: 'canvas',
  resolveConcurrencyKey: (input) => `canvas:${input.projectId}`,
  resolveTargetIds: (input) => target(input.projectId, { assetId: input.assetId }),
  summarize: (output) => `已将素材 ${output.assetId} 放入画布节点 ${output.nodeId}。`,
  createUndo: (output) => ({ kind: 'canvas_history', token: output.undoRef }),
})

const addGenerationResultToCanvas = defineApplicationCapability({
  id: 'add_generation_result_to_canvas',
  version: 1,
  title: '把生成结果放入画布',
  description: '按稳定 generation.result 引用把已成功生成的媒体直接落成画布源节点，不要求先导入素材库。',
  domain: 'canvas',
  aliases: ['把生成结果放入画布', '生成图片加入画布', 'add generation result to canvas'],
  readOnly: false,
  control: capabilityControl('create', ['canvas.node'], { revisionScopes: ['canvas'] }),
  risk: 'R1',
  dataClasses: ['C1'],
  permission: 'canvas:write',
  idempotent: true,
  destructive: false,
  timeoutMs: 12_000,
  supportsPreview: false,
  supportsUndo: true,
  requiredScopes: ['canvas', 'generation'],
  prerequisites: ['resultRef 必须来自已成功且 resultAvailable=true 的正式生成任务。'],
  acceptsRefs: ['canvas.project', 'generation.result'],
  producesRefs: ['canvas.node', 'generation.result'],
  inputSchema: z.object({
    projectId: z.string().min(1),
    resultRef: z.object({
      kind: z.literal('generation.result'),
      id: z.string().min(1),
    }).strict(),
    placement: canvasNodePlacementSchema,
  }).strict(),
  outputSchema: capabilityOutputSchema({
    projectId: z.string(),
    resultRef: z.object({ kind: z.literal('generation.result'), id: z.string() }).strict(),
    mediaType: z.enum(['image', 'video', 'audio']),
    nodeId: z.string(),
    nodeType: z.string(),
    nodeRef: z.object({ kind: z.literal('canvas.node'), id: z.string() }).strict(),
    undoRef: z.string(),
  }),
  concurrencyKey: 'canvas',
  resolveConcurrencyKey: (input) => `canvas:${input.projectId}`,
  resolveTargetIds: (input) => target(input.projectId, { resultId: input.resultRef.id }),
  summarize: (output) => `已将生成结果 ${output.resultRef.id} 放入画布节点 ${output.nodeId}。`,
  createUndo: (output) => ({ kind: 'canvas_history', token: output.undoRef }),
  successEvidence: ['返回实际创建的 canvas.node 稳定引用，且可由正式画布读取能力复核。'],
  failureRecovery: ['结果尚未完成时等待原生成任务；引用失效时重新读取生成任务，禁止改用素材 ID 猜测。'],
  resolveObservedEffects: (_input, output) => [{
    effect: 'create', entityTypes: ['canvas.node'], propertyIds: [],
    targetRefs: [output.nodeRef], count: 1, verified: false,
    evidence: [`node:${output.nodeRef.id}`],
  }],
})

const connectCanvasNodes = defineApplicationCapability({
  id: 'connect_canvas_nodes',
  version: 1,
  title: '连接画布节点',
  description: '连接明确的上下游节点，由宿主拒绝不兼容、重复或循环连接。',
  domain: 'canvas',
  aliases: ['连接节点', 'connect canvas nodes'],
  readOnly: false,
  risk: 'R1',
  dataClasses: ['C1'],
  permission: 'canvas:write',
  idempotent: true,
  destructive: false,
  timeoutMs: 8_000,
  supportsPreview: false,
  supportsUndo: true,
  requiredScopes: ['canvas'],
  acceptsRefs: ['canvas.project', 'canvas.node'],
  producesRefs: ['canvas.edge', 'canvas.node'],
  executionPrerequisites: ['add_canvas_node'],
  inputSchema: z.object({
    projectId: z.string().min(1),
    sourceNodeId: z.string().min(1),
    targetNodeId: z.string().min(1),
    sourceHandle: z.string().min(1).max(160).optional(),
    targetHandle: z.string().min(1).max(160).optional(),
  }).strict(),
  outputSchema: capabilityOutputSchema({
    projectId: z.string(),
    edgeId: z.string(),
    sourceNodeId: z.string(),
    targetNodeId: z.string(),
    effectiveSourceNodeId: z.string(),
    createdNodeIds: z.array(z.string()).optional(),
    createdEdgeIds: z.array(z.string()).optional(),
    sourceHandle: z.string(),
    targetHandle: z.string(),
    undoRef: z.string(),
  }),
  concurrencyKey: 'canvas',
  resolveConcurrencyKey: (input) => `canvas:${input.projectId}`,
  resolveTargetIds: (input) => target(input.projectId, {
    sourceNodeId: input.sourceNodeId,
    targetNodeId: input.targetNodeId,
    ...(input.sourceHandle ? { sourceHandle: input.sourceHandle } : {}),
    ...(input.targetHandle ? { targetHandle: input.targetHandle } : {}),
  }),
  summarize: (output) => `已创建画布连接 ${output.edgeId}。`,
  createUndo: (output) => ({ kind: 'canvas_history', token: output.undoRef }),
  control: { execution: { mode: 'immediate', cancelable: false, resultState: 'completed' }, impacts: [{
    effect: 'create', entityTypes: ['canvas.edge'], propertyIds: [], revisionScopes: ['canvas'], verificationRequired: true,
  }, {
    effect: 'create', entityTypes: ['canvas.node'], propertyIds: [], revisionScopes: ['canvas'], verificationRequired: true,
  }] },
  resolveObservedEffects: (_input, output) => {
    const edgeIds = output.createdEdgeIds?.length ? output.createdEdgeIds : [output.edgeId]
    return [{
      effect: 'create' as const, entityTypes: ['canvas.edge'], propertyIds: [],
      targetRefs: edgeIds.map((id) => ({ kind: 'canvas.edge' as const, id })),
      count: edgeIds.length, verified: false,
      evidence: edgeIds.map((id) => `edge:${id}`),
    }, ...(output.createdNodeIds?.length ? [{
      effect: 'create' as const, entityTypes: ['canvas.node'], propertyIds: [],
      targetRefs: output.createdNodeIds.map((id) => ({ kind: 'canvas.node' as const, id })),
      count: output.createdNodeIds.length, verified: false,
      evidence: output.createdNodeIds.map((id) => `node:${id}`),
    }] : [])]
  },
})

const focusCanvasNode = defineApplicationCapability({
  id: 'focus_canvas_node',
  version: 2,
  title: '定位画布节点',
  description: '进入画布工作区，选中并把明确节点定位到可视区域。',
  domain: 'canvas',
  aliases: ['查看画布节点', 'focus canvas node'],
  readOnly: false,
  control: capabilityControl('navigate', ['canvas.node', 'application.surface']),
  risk: 'R0',
  dataClasses: ['C1'],
  permission: 'canvas:focus',
  idempotent: true,
  destructive: false,
  timeoutMs: 12_000,
  supportsPreview: false,
  supportsUndo: false,
  requiredScopes: ['navigation', 'canvas'],
  acceptsRefs: ['canvas.project', 'canvas.node'],
  producesRefs: ['application.entity', 'application.surface'],
  successEvidence: ['目标项目已载入，返回并验证 Surface ID workspace.canvas，且节点已在画布可视区域中获得焦点。'],
  failureRecovery: ['项目或节点不存在时重新读取明确引用；画布无法定位时停止并说明，不猜测其它节点。'],
  inputSchema: z.object({
    projectId: z.string().min(1),
    nodeId: z.string().min(1),
  }).strict(),
  outputSchema: capabilityOutputSchema({
    projectId: z.string(),
    nodeId: z.string(),
    focused: z.boolean(),
    surfaceId: z.literal('workspace.canvas'),
  }),
  concurrencyKey: 'canvas_focus',
  resolveTargetIds: (input) => target(input.projectId, { nodeId: input.nodeId }),
  summarize: (output) => `已定位画布节点 ${output.nodeId}。`,
})

const undoCanvasChange = defineApplicationCapability({
  id: 'undo_canvas_change',
  version: 1,
  title: '撤销画布操作',
  description: '使用上一条画布写操作返回的撤销引用进行后进先出撤销。',
  domain: 'canvas',
  aliases: ['撤销节点操作', 'undo canvas change'],
  readOnly: false,
  control: capabilityControl('execute', ['canvas.project'], { revisionScopes: ['canvas'] }),
  risk: 'R1',
  dataClasses: ['C1'],
  permission: 'canvas:undo',
  idempotent: true,
  destructive: true,
  timeoutMs: 8_000,
  supportsPreview: false,
  supportsUndo: false,
  requiredScopes: ['canvas'],
  acceptsRefs: ['canvas.undo'],
  producesRefs: ['canvas.project'],
  inputSchema: z.object({
    projectId: z.string().min(1),
    undoRef: z.string().min(1),
  }).strict(),
  outputSchema: capabilityOutputSchema({
    projectId: z.string(),
    undoRef: z.string(),
    operation: z.string(),
    status: z.literal('undone'),
  }),
  concurrencyKey: 'canvas',
  resolveConcurrencyKey: (input) => `canvas:${input.projectId}`,
  resolveTargetIds: (input) => target(input.projectId, { undoRef: input.undoRef }),
  summarize: (output) => `已撤销画布操作 ${output.operation}。`,
})

const redoCanvasChange = defineApplicationCapability({
  id: 'redo_canvas_change',
  version: 1,
  title: '重做画布操作',
  description: '重做最近一次被撤销的画布写操作。',
  domain: 'canvas',
  aliases: ['重做节点操作', 'redo canvas change'],
  readOnly: false,
  control: capabilityControl('execute', ['canvas.project'], { revisionScopes: ['canvas'] }),
  risk: 'R1',
  dataClasses: ['C1'],
  permission: 'canvas:undo',
  idempotent: true,
  destructive: true,
  timeoutMs: 8_000,
  supportsPreview: false,
  supportsUndo: false,
  requiredScopes: ['canvas'],
  acceptsRefs: ['canvas.project'],
  producesRefs: ['canvas.project'],
  inputSchema: z.object({
    projectId: z.string().min(1),
  }).strict(),
  outputSchema: capabilityOutputSchema({
    projectId: z.string(),
    status: z.literal('redone'),
  }),
  concurrencyKey: 'canvas',
  resolveConcurrencyKey: (input) => `canvas:${input.projectId}`,
  resolveTargetIds: (input) => target(input.projectId),
  summarize: (output) => `已重做项目 ${output.projectId} 的画布操作。`,
})

const duplicateCanvasNode = defineApplicationCapability({
  id: 'duplicate_canvas_node',
  version: 1,
  title: '复制画布节点',
  description: '复制明确节点的安全配置，并按确定性布局放置。',
  domain: 'canvas',
  aliases: ['复制节点', 'duplicate canvas node'],
  readOnly: false,
  risk: 'R1',
  dataClasses: ['C1'],
  permission: 'canvas:write',
  idempotent: false,
  destructive: false,
  timeoutMs: 8_000,
  supportsPreview: false,
  supportsUndo: true,
  requiredScopes: ['canvas'],
  acceptsRefs: ['canvas.project', 'canvas.node'],
  producesRefs: ['canvas.node'],
  inputSchema: z.object({
    projectId: z.string().min(1),
    nodeId: z.string().min(1),
    placement: canvasNodePlacementSchema,
  }).strict(),
  outputSchema: capabilityOutputSchema({
    projectId: z.string(),
    nodeId: z.string(),
    duplicatedFromNodeId: z.string(),
    undoRef: z.string(),
  }),
  concurrencyKey: 'canvas',
  resolveConcurrencyKey: (input) => `canvas:${input.projectId}`,
  resolveTargetIds: (input) => target(input.projectId, { nodeId: input.nodeId }),
  summarize: (output) => `已复制画布节点 ${output.duplicatedFromNodeId} 为 ${output.nodeId}。`,
  createUndo: (output) => ({ kind: 'canvas_history', token: output.undoRef }),
  control: { execution: { mode: 'immediate', cancelable: false, resultState: 'completed' }, impacts: [{
    effect: 'create', entityTypes: ['canvas.node'], propertyIds: [], revisionScopes: ['canvas'], verificationRequired: true,
  }] },
})

const updateCanvasNode = defineApplicationCapability({
  id: 'update_canvas_node',
  version: 1,
  title: '更新画布节点',
  description: '按照节点结构更新明确节点的可编辑数据。',
  domain: 'canvas',
  aliases: ['修改节点参数', 'update canvas node'],
  readOnly: false,
  risk: 'R1',
  dataClasses: ['C1'],
  permission: 'canvas:write',
  idempotent: true,
  destructive: false,
  timeoutMs: 8_000,
  supportsPreview: false,
  supportsUndo: true,
  requiredScopes: ['canvas'],
  acceptsRefs: ['canvas.project', 'canvas.node'],
  producesRefs: ['canvas.node'],
  inputSchema: z.object({
    projectId: z.string().min(1),
    nodeId: z.string().min(1),
    data: z.record(z.string(), z.unknown()),
  }).strict(),
  outputSchema: capabilityOutputSchema({
    projectId: z.string(),
    nodeId: z.string(),
    updatedKeys: z.array(z.string()),
    undoRef: z.string(),
  }),
  concurrencyKey: 'canvas_node',
  resolveConcurrencyKey: (input) => `canvas:${input.projectId}:${input.nodeId}`,
  resolveTargetIds: (input) => target(input.projectId, { nodeId: input.nodeId }),
  summarize: (output) => `已更新画布节点 ${output.nodeId}。`,
  createUndo: (output) => ({ kind: 'canvas_history', token: output.undoRef }),
  control: { execution: { mode: 'immediate', cancelable: false, resultState: 'completed' }, impacts: [{
    effect: 'update', entityTypes: ['canvas.node'], propertyIds: [], revisionScopes: ['canvas'], verificationRequired: true,
  }] },
  resolveObservedEffects: (input, output) => [{
    effect: 'update', entityTypes: ['canvas.node'],
    propertyIds: Object.keys(input.data).map((key) => `canvas.node.${key}`),
    targetRefs: [{ kind: 'canvas.node', id: input.nodeId }], count: 1, verified: false,
    evidence: [`node:${output.nodeId}`],
  }],
})

const deleteCanvasNodes = defineApplicationCapability({
  id: 'delete_canvas_nodes',
  version: 1,
  title: '删除画布节点',
  description: '删除明确的画布节点及关联边，并返回可撤销引用。',
  domain: 'canvas',
  aliases: ['删除节点', 'delete canvas nodes'],
  readOnly: false,
  risk: 'R2',
  dataClasses: ['C1'],
  permission: 'canvas:write',
  idempotent: true,
  destructive: true,
  timeoutMs: 8_000,
  supportsPreview: true,
  supportsUndo: true,
  requiredScopes: ['canvas'],
  acceptsRefs: ['canvas.project', 'canvas.node'],
  producesRefs: ['canvas.undo'],
  inputSchema: z.object({
    projectId: z.string().min(1),
    nodeIds: z.array(z.string().min(1)).min(1).max(50),
  }).strict(),
  outputSchema: capabilityOutputSchema({
    projectId: z.string(),
    deletedNodeIds: z.array(z.string()),
    undoRef: z.string(),
  }),
  concurrencyKey: 'canvas',
  resolveConcurrencyKey: (input) => `canvas:${input.projectId}`,
  resolveTargetIds: (input) => target(input.projectId, { nodeIds: input.nodeIds.join(',') }),
  preview: (input) => ({
    title: '删除画布节点',
    summary: `删除 ${input.nodeIds.length} 个节点及关联边。`,
    targetIds: target(input.projectId, { nodeIds: input.nodeIds.join(',') }),
    reversible: true,
    dataClasses: ['C1'],
  }),
  summarize: (output) => `已删除 ${output.deletedNodeIds.length} 个画布节点。`,
  createUndo: (output) => ({ kind: 'canvas_history', token: output.undoRef }),
  control: { execution: { mode: 'confirmation_required', cancelable: false, resultState: 'completed' }, impacts: [{
    effect: 'delete', entityTypes: ['canvas.node'], propertyIds: [], revisionScopes: ['canvas'], verificationRequired: true,
  }] },
  resolveObservedEffects: (input, output) => [{
    effect: 'delete', entityTypes: ['canvas.node'], propertyIds: [],
    targetRefs: input.nodeIds.map((id) => ({ kind: 'canvas.node', id })), count: input.nodeIds.length,
    verified: false, evidence: [`undo:${output.undoRef}`],
  }],
})

const selectCanvasNode = defineApplicationCapability({
  id: 'select_canvas_node',
  version: 1,
  title: '选择画布节点',
  description: '在明确项目中选择或清除一个节点，不改变画布数据。',
  domain: 'canvas',
  aliases: ['选中节点', 'select canvas node'],
  readOnly: false,
  risk: 'R0',
  dataClasses: ['C0'],
  permission: 'canvas:selection',
  idempotent: true,
  destructive: false,
  timeoutMs: 5_000,
  supportsPreview: false,
  supportsUndo: false,
  requiredScopes: ['canvas'],
  acceptsRefs: ['canvas.project', 'canvas.node'],
  producesRefs: ['canvas.node'],
  inputSchema: z.object({
    projectId: z.string().min(1),
    nodeId: z.string().min(1).nullable(),
  }).strict(),
  outputSchema: capabilityOutputSchema({
    projectId: z.string(),
    selectedNodeId: z.string().nullable(),
  }),
  concurrencyKey: 'canvas_selection',
  resolveConcurrencyKey: (input) => `canvas:${input.projectId}:selection`,
  resolveTargetIds: (input) => target(input.projectId, { nodeId: input.nodeId ?? '' }),
  summarize: (output) => `当前选中节点：${output.selectedNodeId ?? '无'}。`,
  control: { execution: { mode: 'immediate', cancelable: false, resultState: 'completed' }, impacts: [{
    effect: 'update', entityTypes: ['canvas.project'], propertyIds: ['canvas.project.selected_node'], revisionScopes: ['canvas'], verificationRequired: false,
  }] },
})

const groupCanvasNodes = defineApplicationCapability({
  id: 'group_canvas_nodes',
  version: 1,
  title: '组合画布节点',
  description: '把明确的两个或多个节点放入空间组或素材组；默认创建空间组。',
  domain: 'canvas',
  aliases: ['节点分组', 'group canvas nodes'],
  readOnly: false,
  risk: 'R1',
  dataClasses: ['C1'],
  permission: 'canvas:write',
  idempotent: false,
  destructive: false,
  timeoutMs: 8_000,
  supportsPreview: false,
  supportsUndo: true,
  requiredScopes: ['canvas'],
  acceptsRefs: ['canvas.project', 'canvas.node'],
  producesRefs: ['canvas.node'],
  inputSchema: z.object({
    projectId: z.string().min(1),
    nodeIds: z.array(z.string().min(1)).min(2).max(50),
    groupKind: z.enum(['spatial', 'asset']).optional().default('spatial'),
  }).strict(),
  outputSchema: capabilityOutputSchema({
    projectId: z.string(),
    groupNodeId: z.string(),
    groupKind: z.enum(['spatial', 'asset']),
    accepted: z.number().int().nonnegative().optional(),
    undoRef: z.string(),
  }),
  concurrencyKey: 'canvas',
  resolveConcurrencyKey: (input) => `canvas:${input.projectId}`,
  resolveTargetIds: (input) => target(input.projectId, { nodeIds: input.nodeIds.join(',') }),
  summarize: (output) => `已创建节点组 ${output.groupNodeId}。`,
  createUndo: (output) => ({ kind: 'canvas_history', token: output.undoRef }),
  control: { execution: { mode: 'immediate', cancelable: false, resultState: 'completed' }, impacts: [{
    effect: 'create', entityTypes: ['canvas.node'], propertyIds: [], revisionScopes: ['canvas'], verificationRequired: true,
  }] },
})

const connectAssetGroupToTarget = defineApplicationCapability({
  id: 'connect_asset_group_to_target',
  version: 1,
  title: '连接素材组到目标节点',
  description: '为素材组建立持久目标绑定，并按可见媒体接口、容量和成员顺序同步真实独立连线。',
  domain: 'canvas',
  aliases: ['绑定素材组', 'connect asset group'],
  readOnly: false,
  risk: 'R1',
  dataClasses: ['C1'],
  permission: 'canvas:write',
  idempotent: true,
  destructive: false,
  timeoutMs: 8_000,
  supportsPreview: false,
  supportsUndo: true,
  requiredScopes: ['canvas'],
  acceptsRefs: ['canvas.project', 'canvas.node'],
  producesRefs: ['canvas.edge', 'canvas.undo'],
  inputSchema: z.object({
    projectId: z.string().min(1),
    groupNodeId: z.string().min(1),
    targetNodeId: z.string().min(1),
  }).strict(),
  outputSchema: capabilityOutputSchema({
    projectId: z.string(),
    groupNodeId: z.string(),
    targetNodeId: z.string(),
    connected: z.number().int().nonnegative(),
    pending: z.number().int().nonnegative(),
    unsupported: z.number().int().nonnegative(),
    excluded: z.number().int().nonnegative(),
    undoRef: z.string(),
  }),
  concurrencyKey: 'canvas',
  resolveConcurrencyKey: (input) => `canvas:${input.projectId}`,
  resolveTargetIds: (input) => target(input.projectId, {
    groupNodeId: input.groupNodeId,
    targetNodeId: input.targetNodeId,
  }),
  summarize: (output) => `素材组已连接 ${output.connected} 个成员，${output.pending} 个等待容量。`,
  createUndo: (output) => ({ kind: 'canvas_history', token: output.undoRef }),
  control: { execution: { mode: 'immediate', cancelable: false, resultState: 'completed' }, impacts: [{
    effect: 'create', entityTypes: ['canvas.edge'], propertyIds: [], revisionScopes: ['canvas'], verificationRequired: true,
  }] },
})

const disconnectAssetGroupFromTarget = defineApplicationCapability({
  id: 'disconnect_asset_group_from_target',
  version: 1,
  title: '断开素材组目标绑定',
  description: '解除素材组与明确目标节点的绑定，只删除该绑定管理的连线。',
  domain: 'canvas',
  aliases: ['解除素材组绑定', 'disconnect asset group'],
  readOnly: false,
  risk: 'R1',
  dataClasses: ['C1'],
  permission: 'canvas:write',
  idempotent: true,
  destructive: true,
  timeoutMs: 8_000,
  supportsPreview: false,
  supportsUndo: true,
  requiredScopes: ['canvas'],
  acceptsRefs: ['canvas.project', 'canvas.node'],
  producesRefs: ['canvas.undo'],
  inputSchema: z.object({
    projectId: z.string().min(1),
    groupNodeId: z.string().min(1),
    targetNodeId: z.string().min(1),
  }).strict(),
  outputSchema: capabilityOutputSchema({
    projectId: z.string(),
    groupNodeId: z.string(),
    targetNodeId: z.string(),
    undoRef: z.string(),
  }),
  concurrencyKey: 'canvas',
  resolveConcurrencyKey: (input) => `canvas:${input.projectId}`,
  resolveTargetIds: (input) => target(input.projectId, {
    groupNodeId: input.groupNodeId,
    targetNodeId: input.targetNodeId,
  }),
  summarize: (output) => `已解除素材组 ${output.groupNodeId} 与目标 ${output.targetNodeId} 的绑定。`,
  createUndo: (output) => ({ kind: 'canvas_history', token: output.undoRef }),
  control: { execution: { mode: 'immediate', cancelable: false, resultState: 'completed' }, impacts: [{
    effect: 'delete', entityTypes: ['canvas.edge'], propertyIds: [], revisionScopes: ['canvas'], verificationRequired: true,
  }] },
})

const ungroupCanvasNode = defineApplicationCapability({
  id: 'ungroup_canvas_node',
  version: 1,
  title: '解散画布节点分组',
  description: '解散明确的组节点，子节点保留在画布上并释放出来。',
  domain: 'canvas',
  aliases: ['取消节点分组', 'ungroup canvas node'],
  readOnly: false,
  risk: 'R1',
  dataClasses: ['C1'],
  permission: 'canvas:write',
  idempotent: false,
  destructive: false,
  timeoutMs: 8_000,
  supportsPreview: false,
  supportsUndo: true,
  requiredScopes: ['canvas'],
  acceptsRefs: ['canvas.project', 'canvas.node'],
  producesRefs: ['canvas.undo'],
  inputSchema: z.object({
    projectId: z.string().min(1),
    groupNodeId: z.string().min(1),
  }).strict(),
  outputSchema: capabilityOutputSchema({
    projectId: z.string(),
    groupNodeId: z.string(),
    undoRef: z.string(),
  }),
  concurrencyKey: 'canvas',
  resolveConcurrencyKey: (input) => `canvas:${input.projectId}`,
  resolveTargetIds: (input) => target(input.projectId, { groupNodeId: input.groupNodeId }),
  summarize: (output) => `已解散节点组 ${output.groupNodeId}。`,
  createUndo: (output) => ({ kind: 'canvas_history', token: output.undoRef }),
  control: { execution: { mode: 'immediate', cancelable: false, resultState: 'completed' }, impacts: [{
    effect: 'delete', entityTypes: ['canvas.node'], propertyIds: [], revisionScopes: ['canvas'], verificationRequired: true,
  }] },
})

const clearCanvas = defineApplicationCapability({
  id: 'clear_canvas',
  version: 1,
  title: '清空画布',
  description: '删除明确项目中的全部节点与连线，返回可撤销引用。',
  domain: 'canvas',
  aliases: ['清空画布节点', 'clear canvas'],
  readOnly: false,
  risk: 'R2',
  dataClasses: ['C1'],
  permission: 'canvas:write',
  idempotent: true,
  destructive: true,
  timeoutMs: 8_000,
  supportsPreview: true,
  supportsUndo: true,
  requiredScopes: ['canvas'],
  acceptsRefs: ['canvas.project'],
  producesRefs: ['canvas.undo'],
  inputSchema: z.object({
    projectId: z.string().min(1),
  }).strict(),
  outputSchema: capabilityOutputSchema({
    projectId: z.string(),
    clearedNodeCount: z.number().int().nonnegative(),
    clearedEdgeCount: z.number().int().nonnegative(),
    undoRef: z.string(),
  }),
  concurrencyKey: 'canvas',
  resolveConcurrencyKey: (input) => `canvas:${input.projectId}`,
  resolveTargetIds: (input) => target(input.projectId),
  preview: (input) => ({
    title: '清空画布',
    summary: '删除该项目中的全部节点与连线。',
    targetIds: target(input.projectId),
    reversible: true,
    dataClasses: ['C1'],
  }),
  summarize: (output) => `已清空画布，删除 ${output.clearedNodeCount} 个节点、${output.clearedEdgeCount} 条连线。`,
  createUndo: (output) => ({ kind: 'canvas_history', token: output.undoRef }),
  control: { execution: { mode: 'confirmation_required', cancelable: false, resultState: 'completed' }, impacts: [{
    effect: 'delete', entityTypes: ['canvas.node', 'canvas.edge'], propertyIds: [], revisionScopes: ['canvas'], verificationRequired: true,
  }] },
})

const disconnectCanvasEdge = defineApplicationCapability({
  id: 'disconnect_canvas_edge',
  version: 1,
  title: '断开画布连接',
  description: '按明确连接引用断开画布连接。',
  domain: 'canvas',
  aliases: ['删除节点连线', 'disconnect canvas edge'],
  readOnly: false,
  risk: 'R1',
  dataClasses: ['C1'],
  permission: 'canvas:write',
  idempotent: true,
  destructive: true,
  timeoutMs: 8_000,
  supportsPreview: false,
  supportsUndo: true,
  requiredScopes: ['canvas'],
  acceptsRefs: ['canvas.project', 'canvas.edge'],
  producesRefs: ['canvas.undo'],
  inputSchema: z.object({
    projectId: z.string().min(1),
    edgeId: z.string().min(1),
  }).strict(),
  outputSchema: capabilityOutputSchema({
    projectId: z.string(),
    edgeId: z.string(),
    undoRef: z.string(),
  }),
  concurrencyKey: 'canvas',
  resolveConcurrencyKey: (input) => `canvas:${input.projectId}`,
  resolveTargetIds: (input) => target(input.projectId, { edgeId: input.edgeId }),
  summarize: (output) => `已断开画布连接 ${output.edgeId}。`,
  createUndo: (output) => ({ kind: 'canvas_history', token: output.undoRef }),
  control: { execution: { mode: 'immediate', cancelable: false, resultState: 'completed' }, impacts: [{
    effect: 'delete', entityTypes: ['canvas.edge'], propertyIds: [], revisionScopes: ['canvas'], verificationRequired: true,
  }] },
})

export const EXPORT_IMAGE_EDIT_TARGET_TO_CANVAS_CAPABILITY_ID = 'export_image_edit_target_to_canvas'

const canvasProjectRefSchema = applicationRefSchema.extend({
  kind: z.literal('canvas.project'),
}).strict()
const canvasNodeRefSchema = applicationRefSchema.extend({
  kind: z.literal('canvas.node'),
}).strict()
const canvasEdgeRefSchema = applicationRefSchema.extend({
  kind: z.literal('canvas.edge'),
}).strict()
const imageEditExportTargetRefSchema = applicationRefSchema.extend({
  kind: z.enum(['image_edit.layer', 'image_edit.group', 'image_mark.annotation']),
}).strict()

const exportImageEditTargetToCanvas = defineApplicationCapability({
  id: EXPORT_IMAGE_EDIT_TARGET_TO_CANVAS_CAPABILITY_ID,
  version: 1,
  title: '导出图片编辑目标到画布',
  description: '把当前多图层图片文档中的单个栅格图层、图层组或标注元素原子导出为普通图片节点并连接来源。',
  domain: 'image_edit',
  aliases: ['导出图层到画布', '导出元素到画布', 'export layer to canvas', 'export element to canvas'],
  readOnly: false,
  risk: 'R1',
  dataClasses: ['C1'],
  permission: 'canvas:write',
  idempotent: false,
  destructive: false,
  timeoutMs: 120_000,
  supportsPreview: false,
  supportsUndo: true,
  requiredScopes: ['image_edit', 'canvas'],
  parallelSafe: false,
  availability: ['当前画布项目已打开', '来源节点是可编辑的多图层图片文档', '目标是受支持的稳定图片编辑引用'],
  prerequisites: [
    '目标必须是当前文档内唯一明确的 image_edit.layer、image_edit.group 或 image_mark.annotation 稳定引用。',
    '效果层、调整层、浮点精度或 HDR 文档不支持本操作。',
  ],
  acceptsRefs: ['canvas.project', 'canvas.node', 'image_edit.layer', 'image_edit.group', 'image_mark.annotation'],
  producesRefs: ['canvas.node', 'canvas.edge'],
  inputSchema: z.object({
    projectRef: canvasProjectRefSchema,
    sourceNodeRef: canvasNodeRefSchema,
    targetRef: imageEditExportTargetRefSchema,
  }).strict(),
  outputSchema: capabilityOutputSchema({
    projectRef: canvasProjectRefSchema,
    sourceNodeRef: canvasNodeRefSchema,
    targetRef: imageEditExportTargetRefSchema,
    nodeRef: canvasNodeRefSchema,
    edgeRef: canvasEdgeRefSchema,
    undoRef: z.string().min(1),
    width: z.number().int().positive(),
    height: z.number().int().positive(),
    mediaType: z.literal('image/png'),
  }),
  concurrencyKey: 'image_edit_export',
  resolveConcurrencyKey: (input) => [
    'image_edit_export',
    input.sourceNodeRef.id,
    input.targetRef.kind,
    input.targetRef.id,
  ].join(':'),
  resolveTargetIds: (input) => ({
    projectId: input.projectRef.id,
    sourceNodeId: input.sourceNodeRef.id,
    targetKind: input.targetRef.kind,
    targetId: input.targetRef.id,
  }),
  summarize: (output) => `已把所选图片编辑目标导出为 ${output.width}×${output.height} 的普通图片节点。`,
  createUndo: (output) => ({ kind: 'canvas_history', token: output.undoRef }),
  control: capabilityControl('create', ['canvas.node'], {
    revisionScopes: ['canvas'],
    verificationRequired: true,
    cancelable: true,
    alsoImpacts: [{ effect: 'create', entityTypes: ['canvas.edge'] }],
  }),
  successEvidence: ['返回实际创建的 canvas.node、canvas.edge 稳定引用和单次事务撤销引用。'],
  failureRecovery: [
    '物化或画布事务失败时不会修改原文档；新建节点、连线与受管 PNG 会被补偿，可重新读取当前选择后重试。',
  ],
  resolveObservedEffects: (_input, output) => [
    {
      effect: 'create', entityTypes: ['canvas.node'], propertyIds: [],
      targetRefs: [output.nodeRef], count: 1, verified: false,
      evidence: [`node:${output.nodeRef.id}`, `png:${output.width}x${output.height}`],
    },
    {
      effect: 'create', entityTypes: ['canvas.edge'], propertyIds: [],
      targetRefs: [output.edgeRef], count: 1, verified: false,
      evidence: [`edge:${output.edgeRef.id}`],
    },
  ],
})

export const CANVAS_MUTATION_APPLICATION_CAPABILITIES: ApplicationCapabilityDefinition[] = [
  addCanvasNode,
  applyCanvasImageCapability,
  addAssetToCanvas,
  addGenerationResultToCanvas,
  connectCanvasNodes,
  focusCanvasNode,
  undoCanvasChange,
  redoCanvasChange,
  duplicateCanvasNode,
  updateCanvasNode,
  deleteCanvasNodes,
  selectCanvasNode,
  groupCanvasNodes,
  connectAssetGroupToTarget,
  disconnectAssetGroupFromTarget,
  ungroupCanvasNode,
  clearCanvas,
  disconnectCanvasEdge,
  exportImageEditTargetToCanvas,
]
