import { z } from 'zod'

import type { ApplicationCapabilityDefinition } from '../applicationCapabilities'
import {
  capabilityControl,
  capabilityOutputSchema,
  defineApplicationCapability,
} from './defineApplicationCapability'

export const canvasNodePlacementSchema = z.discriminatedUnion('mode', [
  z.object({ mode: z.literal('viewport_center') }).strict(),
  z.object({
    mode: z.literal('right_of_node'),
    anchorNodeId: z.string().min(1),
  }).strict(),
])
export type CanvasNodePlacement = z.infer<typeof canvasNodePlacementSchema>

function target(projectId: string, extra: Record<string, string> = {}): Record<string, string> {
  return { projectId, ...extra }
}

const addCanvasNode = defineApplicationCapability({
  id: 'add_canvas_node',
  version: 1,
  title: '添加画布节点',
  description: '在明确项目中按确定性布局添加已通过节点结构校验的节点。',
  domain: 'canvas',
  aliases: ['新建画布节点', 'add canvas node'],
  readOnly: false,
  risk: 'R1',
  dataClasses: ['C1'],
  permission: 'canvas:write',
  idempotent: true,
  destructive: false,
  timeoutMs: 8_000,
  supportsPreview: false,
  supportsUndo: true,
  requiredScopes: ['canvas'],
  acceptsRefs: ['canvas.project', 'canvas.node_type'],
  producesRefs: ['canvas.node'],
  inputSchema: z.object({
    projectId: z.string().min(1),
    nodeType: z.string().min(1),
    placement: canvasNodePlacementSchema,
    data: z.record(z.string(), z.unknown()).optional(),
  }).strict(),
  outputSchema: capabilityOutputSchema({
    projectId: z.string(),
    nodeId: z.string(),
    nodeType: z.string(),
    undoRef: z.string(),
  }),
  concurrencyKey: 'canvas',
  resolveConcurrencyKey: (input) => `canvas:${input.projectId}`,
  resolveTargetIds: (input) => target(input.projectId, { nodeType: input.nodeType }),
  summarize: (output) => `已在项目 ${output.projectId} 添加节点 ${output.nodeId}。`,
  createUndo: (output) => ({ kind: 'canvas_history', token: output.undoRef }),
  control: { execution: { mode: 'immediate', cancelable: false, resultState: 'completed' }, impacts: [{
    effect: 'create', entityTypes: ['canvas.node'], propertyIds: [], revisionScopes: ['canvas'], verificationRequired: true,
  }] },
})

const addAssetToCanvas = defineApplicationCapability({
  id: 'add_asset_to_canvas',
  version: 1,
  title: '把素材放入画布',
  description: '按稳定素材引用将素材作为受控输入节点放入明确画布项目。',
  domain: 'canvas',
  aliases: ['素材添加到画布', 'add asset to canvas'],
  readOnly: false,
  control: capabilityControl('create', ['canvas.node'], { revisionScopes: ['canvas'] }),
  risk: 'R1',
  dataClasses: ['C1'],
  permission: 'canvas:write',
  idempotent: true,
  destructive: false,
  timeoutMs: 12_000,
  supportsPreview: false,
  supportsUndo: true,
  requiredScopes: ['canvas', 'assets'],
  acceptsRefs: ['canvas.project', 'canvas.node', 'asset'],
  producesRefs: ['canvas.node', 'asset'],
  inputSchema: z.object({
    projectId: z.string().min(1),
    assetId: z.string().min(1),
    placement: canvasNodePlacementSchema,
  }).strict(),
  outputSchema: capabilityOutputSchema({
    projectId: z.string(),
    assetId: z.string(),
    mediaType: z.enum(['image', 'video', 'audio']),
    nodeId: z.string(),
    nodeType: z.string(),
    undoRef: z.string(),
  }),
  concurrencyKey: 'canvas',
  resolveConcurrencyKey: (input) => `canvas:${input.projectId}`,
  resolveTargetIds: (input) => target(input.projectId, { assetId: input.assetId }),
  summarize: (output) => `已将素材 ${output.assetId} 放入画布节点 ${output.nodeId}。`,
  createUndo: (output) => ({ kind: 'canvas_history', token: output.undoRef }),
})

const connectCanvasNodes = defineApplicationCapability({
  id: 'connect_canvas_nodes',
  version: 1,
  title: '连接画布节点',
  description: '连接明确的上下游节点，由宿主拒绝不兼容、重复或循环连接。',
  domain: 'canvas',
  aliases: ['连接节点', 'connect canvas nodes'],
  readOnly: false,
  risk: 'R1',
  dataClasses: ['C1'],
  permission: 'canvas:write',
  idempotent: true,
  destructive: false,
  timeoutMs: 8_000,
  supportsPreview: false,
  supportsUndo: true,
  requiredScopes: ['canvas'],
  acceptsRefs: ['canvas.project', 'canvas.node'],
  producesRefs: ['canvas.edge'],
  inputSchema: z.object({
    projectId: z.string().min(1),
    sourceNodeId: z.string().min(1),
    targetNodeId: z.string().min(1),
  }).strict(),
  outputSchema: capabilityOutputSchema({
    projectId: z.string(),
    edgeId: z.string(),
    sourceNodeId: z.string(),
    targetNodeId: z.string(),
    undoRef: z.string(),
  }),
  concurrencyKey: 'canvas',
  resolveConcurrencyKey: (input) => `canvas:${input.projectId}`,
  resolveTargetIds: (input) => target(input.projectId, {
    sourceNodeId: input.sourceNodeId,
    targetNodeId: input.targetNodeId,
  }),
  summarize: (output) => `已创建画布连接 ${output.edgeId}。`,
  createUndo: (output) => ({ kind: 'canvas_history', token: output.undoRef }),
  control: { execution: { mode: 'immediate', cancelable: false, resultState: 'completed' }, impacts: [{
    effect: 'create', entityTypes: ['canvas.edge'], propertyIds: [], revisionScopes: ['canvas'], verificationRequired: true,
  }] },
})

const focusCanvasNode = defineApplicationCapability({
  id: 'focus_canvas_node',
  version: 2,
  title: '定位画布节点',
  description: '进入画布工作区，选中并把明确节点定位到可视区域。',
  domain: 'canvas',
  aliases: ['查看画布节点', 'focus canvas node'],
  readOnly: false,
  control: capabilityControl('navigate', ['canvas.node', 'application.surface']),
  risk: 'R0',
  dataClasses: ['C1'],
  permission: 'canvas:focus',
  idempotent: true,
  destructive: false,
  timeoutMs: 12_000,
  supportsPreview: false,
  supportsUndo: false,
  requiredScopes: ['navigation', 'canvas'],
  acceptsRefs: ['canvas.project', 'canvas.node'],
  producesRefs: ['application.entity', 'application.surface'],
  successEvidence: ['目标项目已载入，返回并验证 Surface ID workspace.canvas，且节点已在画布可视区域中获得焦点。'],
  failureRecovery: ['项目或节点不存在时重新读取明确引用；画布无法定位时停止并说明，不猜测其它节点。'],
  inputSchema: z.object({
    projectId: z.string().min(1),
    nodeId: z.string().min(1),
  }).strict(),
  outputSchema: capabilityOutputSchema({
    projectId: z.string(),
    nodeId: z.string(),
    focused: z.boolean(),
    surfaceId: z.literal('workspace.canvas'),
  }),
  concurrencyKey: 'canvas_focus',
  resolveTargetIds: (input) => target(input.projectId, { nodeId: input.nodeId }),
  summarize: (output) => `已定位画布节点 ${output.nodeId}。`,
})

const undoCanvasChange = defineApplicationCapability({
  id: 'undo_canvas_change',
  version: 1,
  title: '撤销画布操作',
  description: '使用上一条画布写操作返回的撤销引用进行后进先出撤销。',
  domain: 'canvas',
  aliases: ['撤销节点操作', 'undo canvas change'],
  readOnly: false,
  control: capabilityControl('execute', ['canvas.project'], { revisionScopes: ['canvas'] }),
  risk: 'R1',
  dataClasses: ['C1'],
  permission: 'canvas:undo',
  idempotent: true,
  destructive: true,
  timeoutMs: 8_000,
  supportsPreview: false,
  supportsUndo: false,
  requiredScopes: ['canvas'],
  acceptsRefs: ['canvas.undo'],
  producesRefs: ['canvas.project'],
  inputSchema: z.object({
    projectId: z.string().min(1),
    undoRef: z.string().min(1),
  }).strict(),
  outputSchema: capabilityOutputSchema({
    projectId: z.string(),
    undoRef: z.string(),
    operation: z.string(),
    status: z.literal('undone'),
  }),
  concurrencyKey: 'canvas',
  resolveConcurrencyKey: (input) => `canvas:${input.projectId}`,
  resolveTargetIds: (input) => target(input.projectId, { undoRef: input.undoRef }),
  summarize: (output) => `已撤销画布操作 ${output.operation}。`,
})

const redoCanvasChange = defineApplicationCapability({
  id: 'redo_canvas_change',
  version: 1,
  title: '重做画布操作',
  description: '重做最近一次被撤销的画布写操作。',
  domain: 'canvas',
  aliases: ['重做节点操作', 'redo canvas change'],
  readOnly: false,
  control: capabilityControl('execute', ['canvas.project'], { revisionScopes: ['canvas'] }),
  risk: 'R1',
  dataClasses: ['C1'],
  permission: 'canvas:undo',
  idempotent: true,
  destructive: true,
  timeoutMs: 8_000,
  supportsPreview: false,
  supportsUndo: false,
  requiredScopes: ['canvas'],
  acceptsRefs: ['canvas.project'],
  producesRefs: ['canvas.project'],
  inputSchema: z.object({
    projectId: z.string().min(1),
  }).strict(),
  outputSchema: capabilityOutputSchema({
    projectId: z.string(),
    status: z.literal('redone'),
  }),
  concurrencyKey: 'canvas',
  resolveConcurrencyKey: (input) => `canvas:${input.projectId}`,
  resolveTargetIds: (input) => target(input.projectId),
  summarize: (output) => `已重做项目 ${output.projectId} 的画布操作。`,
})

const duplicateCanvasNode = defineApplicationCapability({
  id: 'duplicate_canvas_node',
  version: 1,
  title: '复制画布节点',
  description: '复制明确节点的安全配置，并按确定性布局放置。',
  domain: 'canvas',
  aliases: ['复制节点', 'duplicate canvas node'],
  readOnly: false,
  risk: 'R1',
  dataClasses: ['C1'],
  permission: 'canvas:write',
  idempotent: false,
  destructive: false,
  timeoutMs: 8_000,
  supportsPreview: false,
  supportsUndo: true,
  requiredScopes: ['canvas'],
  acceptsRefs: ['canvas.project', 'canvas.node'],
  producesRefs: ['canvas.node'],
  inputSchema: z.object({
    projectId: z.string().min(1),
    nodeId: z.string().min(1),
    placement: canvasNodePlacementSchema,
  }).strict(),
  outputSchema: capabilityOutputSchema({
    projectId: z.string(),
    nodeId: z.string(),
    duplicatedFromNodeId: z.string(),
    undoRef: z.string(),
  }),
  concurrencyKey: 'canvas',
  resolveConcurrencyKey: (input) => `canvas:${input.projectId}`,
  resolveTargetIds: (input) => target(input.projectId, { nodeId: input.nodeId }),
  summarize: (output) => `已复制画布节点 ${output.duplicatedFromNodeId} 为 ${output.nodeId}。`,
  createUndo: (output) => ({ kind: 'canvas_history', token: output.undoRef }),
  control: { execution: { mode: 'immediate', cancelable: false, resultState: 'completed' }, impacts: [{
    effect: 'create', entityTypes: ['canvas.node'], propertyIds: [], revisionScopes: ['canvas'], verificationRequired: true,
  }] },
})

const updateCanvasNode = defineApplicationCapability({
  id: 'update_canvas_node',
  version: 1,
  title: '更新画布节点',
  description: '按照节点结构更新明确节点的可编辑数据。',
  domain: 'canvas',
  aliases: ['修改节点参数', 'update canvas node'],
  readOnly: false,
  risk: 'R1',
  dataClasses: ['C1'],
  permission: 'canvas:write',
  idempotent: true,
  destructive: false,
  timeoutMs: 8_000,
  supportsPreview: false,
  supportsUndo: true,
  requiredScopes: ['canvas'],
  acceptsRefs: ['canvas.project', 'canvas.node'],
  producesRefs: ['canvas.node'],
  inputSchema: z.object({
    projectId: z.string().min(1),
    nodeId: z.string().min(1),
    data: z.record(z.string(), z.unknown()),
  }).strict(),
  outputSchema: capabilityOutputSchema({
    projectId: z.string(),
    nodeId: z.string(),
    updatedKeys: z.array(z.string()),
    undoRef: z.string(),
  }),
  concurrencyKey: 'canvas_node',
  resolveConcurrencyKey: (input) => `canvas:${input.projectId}:${input.nodeId}`,
  resolveTargetIds: (input) => target(input.projectId, { nodeId: input.nodeId }),
  summarize: (output) => `已更新画布节点 ${output.nodeId}。`,
  createUndo: (output) => ({ kind: 'canvas_history', token: output.undoRef }),
  control: { execution: { mode: 'immediate', cancelable: false, resultState: 'completed' }, impacts: [{
    effect: 'update', entityTypes: ['canvas.node'], propertyIds: [], revisionScopes: ['canvas'], verificationRequired: true,
  }] },
  resolveObservedEffects: (input, output) => [{
    effect: 'update', entityTypes: ['canvas.node'],
    propertyIds: Object.keys(input.data).map((key) => `canvas.node.${key}`),
    targetRefs: [{ kind: 'canvas.node', id: input.nodeId }], count: 1, verified: false,
    evidence: [`node:${output.nodeId}`],
  }],
})

const deleteCanvasNodes = defineApplicationCapability({
  id: 'delete_canvas_nodes',
  version: 1,
  title: '删除画布节点',
  description: '删除明确的画布节点及关联边，并返回可撤销引用。',
  domain: 'canvas',
  aliases: ['删除节点', 'delete canvas nodes'],
  readOnly: false,
  risk: 'R2',
  dataClasses: ['C1'],
  permission: 'canvas:write',
  idempotent: true,
  destructive: true,
  timeoutMs: 8_000,
  supportsPreview: true,
  supportsUndo: true,
  requiredScopes: ['canvas'],
  acceptsRefs: ['canvas.project', 'canvas.node'],
  producesRefs: ['canvas.undo'],
  inputSchema: z.object({
    projectId: z.string().min(1),
    nodeIds: z.array(z.string().min(1)).min(1).max(50),
  }).strict(),
  outputSchema: capabilityOutputSchema({
    projectId: z.string(),
    deletedNodeIds: z.array(z.string()),
    undoRef: z.string(),
  }),
  concurrencyKey: 'canvas',
  resolveConcurrencyKey: (input) => `canvas:${input.projectId}`,
  resolveTargetIds: (input) => target(input.projectId, { nodeIds: input.nodeIds.join(',') }),
  preview: (input) => ({
    title: '删除画布节点',
    summary: `删除 ${input.nodeIds.length} 个节点及关联边。`,
    targetIds: target(input.projectId, { nodeIds: input.nodeIds.join(',') }),
    reversible: true,
    dataClasses: ['C1'],
  }),
  summarize: (output) => `已删除 ${output.deletedNodeIds.length} 个画布节点。`,
  createUndo: (output) => ({ kind: 'canvas_history', token: output.undoRef }),
  control: { execution: { mode: 'confirmation_required', cancelable: false, resultState: 'completed' }, impacts: [{
    effect: 'delete', entityTypes: ['canvas.node'], propertyIds: [], revisionScopes: ['canvas'], verificationRequired: true,
  }] },
  resolveObservedEffects: (input, output) => [{
    effect: 'delete', entityTypes: ['canvas.node'], propertyIds: [],
    targetRefs: input.nodeIds.map((id) => ({ kind: 'canvas.node', id })), count: input.nodeIds.length,
    verified: false, evidence: [`undo:${output.undoRef}`],
  }],
})

const selectCanvasNode = defineApplicationCapability({
  id: 'select_canvas_node',
  version: 1,
  title: '选择画布节点',
  description: '在明确项目中选择或清除一个节点，不改变画布数据。',
  domain: 'canvas',
  aliases: ['选中节点', 'select canvas node'],
  readOnly: false,
  risk: 'R0',
  dataClasses: ['C0'],
  permission: 'canvas:selection',
  idempotent: true,
  destructive: false,
  timeoutMs: 5_000,
  supportsPreview: false,
  supportsUndo: false,
  requiredScopes: ['canvas'],
  acceptsRefs: ['canvas.project', 'canvas.node'],
  producesRefs: ['canvas.node'],
  inputSchema: z.object({
    projectId: z.string().min(1),
    nodeId: z.string().min(1).nullable(),
  }).strict(),
  outputSchema: capabilityOutputSchema({
    projectId: z.string(),
    selectedNodeId: z.string().nullable(),
  }),
  concurrencyKey: 'canvas_selection',
  resolveConcurrencyKey: (input) => `canvas:${input.projectId}:selection`,
  resolveTargetIds: (input) => target(input.projectId, { nodeId: input.nodeId ?? '' }),
  summarize: (output) => `当前选中节点：${output.selectedNodeId ?? '无'}。`,
  control: { execution: { mode: 'immediate', cancelable: false, resultState: 'completed' }, impacts: [{
    effect: 'update', entityTypes: ['canvas.project'], propertyIds: ['canvas.project.selected_node'], revisionScopes: ['canvas'], verificationRequired: false,
  }] },
})

const groupCanvasNodes = defineApplicationCapability({
  id: 'group_canvas_nodes',
  version: 1,
  title: '组合画布节点',
  description: '把明确的两个或多个节点放入一个组节点。',
  domain: 'canvas',
  aliases: ['节点分组', 'group canvas nodes'],
  readOnly: false,
  risk: 'R1',
  dataClasses: ['C1'],
  permission: 'canvas:write',
  idempotent: false,
  destructive: false,
  timeoutMs: 8_000,
  supportsPreview: false,
  supportsUndo: true,
  requiredScopes: ['canvas'],
  acceptsRefs: ['canvas.project', 'canvas.node'],
  producesRefs: ['canvas.node'],
  inputSchema: z.object({
    projectId: z.string().min(1),
    nodeIds: z.array(z.string().min(1)).min(2).max(50),
  }).strict(),
  outputSchema: capabilityOutputSchema({
    projectId: z.string(),
    groupNodeId: z.string(),
    undoRef: z.string(),
  }),
  concurrencyKey: 'canvas',
  resolveConcurrencyKey: (input) => `canvas:${input.projectId}`,
  resolveTargetIds: (input) => target(input.projectId, { nodeIds: input.nodeIds.join(',') }),
  summarize: (output) => `已创建节点组 ${output.groupNodeId}。`,
  createUndo: (output) => ({ kind: 'canvas_history', token: output.undoRef }),
  control: { execution: { mode: 'immediate', cancelable: false, resultState: 'completed' }, impacts: [{
    effect: 'create', entityTypes: ['canvas.node'], propertyIds: [], revisionScopes: ['canvas'], verificationRequired: true,
  }] },
})

const ungroupCanvasNode = defineApplicationCapability({
  id: 'ungroup_canvas_node',
  version: 1,
  title: '解散画布节点分组',
  description: '解散明确的组节点，子节点保留在画布上并释放出来。',
  domain: 'canvas',
  aliases: ['取消节点分组', 'ungroup canvas node'],
  readOnly: false,
  risk: 'R1',
  dataClasses: ['C1'],
  permission: 'canvas:write',
  idempotent: false,
  destructive: false,
  timeoutMs: 8_000,
  supportsPreview: false,
  supportsUndo: true,
  requiredScopes: ['canvas'],
  acceptsRefs: ['canvas.project', 'canvas.node'],
  producesRefs: ['canvas.undo'],
  inputSchema: z.object({
    projectId: z.string().min(1),
    groupNodeId: z.string().min(1),
  }).strict(),
  outputSchema: capabilityOutputSchema({
    projectId: z.string(),
    groupNodeId: z.string(),
    undoRef: z.string(),
  }),
  concurrencyKey: 'canvas',
  resolveConcurrencyKey: (input) => `canvas:${input.projectId}`,
  resolveTargetIds: (input) => target(input.projectId, { groupNodeId: input.groupNodeId }),
  summarize: (output) => `已解散节点组 ${output.groupNodeId}。`,
  createUndo: (output) => ({ kind: 'canvas_history', token: output.undoRef }),
  control: { execution: { mode: 'immediate', cancelable: false, resultState: 'completed' }, impacts: [{
    effect: 'delete', entityTypes: ['canvas.node'], propertyIds: [], revisionScopes: ['canvas'], verificationRequired: true,
  }] },
})

const clearCanvas = defineApplicationCapability({
  id: 'clear_canvas',
  version: 1,
  title: '清空画布',
  description: '删除明确项目中的全部节点与连线，返回可撤销引用。',
  domain: 'canvas',
  aliases: ['清空画布节点', 'clear canvas'],
  readOnly: false,
  risk: 'R2',
  dataClasses: ['C1'],
  permission: 'canvas:write',
  idempotent: true,
  destructive: true,
  timeoutMs: 8_000,
  supportsPreview: true,
  supportsUndo: true,
  requiredScopes: ['canvas'],
  acceptsRefs: ['canvas.project'],
  producesRefs: ['canvas.undo'],
  inputSchema: z.object({
    projectId: z.string().min(1),
  }).strict(),
  outputSchema: capabilityOutputSchema({
    projectId: z.string(),
    clearedNodeCount: z.number().int().nonnegative(),
    clearedEdgeCount: z.number().int().nonnegative(),
    undoRef: z.string(),
  }),
  concurrencyKey: 'canvas',
  resolveConcurrencyKey: (input) => `canvas:${input.projectId}`,
  resolveTargetIds: (input) => target(input.projectId),
  preview: (input) => ({
    title: '清空画布',
    summary: '删除该项目中的全部节点与连线。',
    targetIds: target(input.projectId),
    reversible: true,
    dataClasses: ['C1'],
  }),
  summarize: (output) => `已清空画布，删除 ${output.clearedNodeCount} 个节点、${output.clearedEdgeCount} 条连线。`,
  createUndo: (output) => ({ kind: 'canvas_history', token: output.undoRef }),
  control: { execution: { mode: 'confirmation_required', cancelable: false, resultState: 'completed' }, impacts: [{
    effect: 'delete', entityTypes: ['canvas.node', 'canvas.edge'], propertyIds: [], revisionScopes: ['canvas'], verificationRequired: true,
  }] },
})

const disconnectCanvasEdge = defineApplicationCapability({
  id: 'disconnect_canvas_edge',
  version: 1,
  title: '断开画布连接',
  description: '按明确连接引用断开画布连接。',
  domain: 'canvas',
  aliases: ['删除节点连线', 'disconnect canvas edge'],
  readOnly: false,
  risk: 'R1',
  dataClasses: ['C1'],
  permission: 'canvas:write',
  idempotent: true,
  destructive: true,
  timeoutMs: 8_000,
  supportsPreview: false,
  supportsUndo: true,
  requiredScopes: ['canvas'],
  acceptsRefs: ['canvas.project', 'canvas.edge'],
  producesRefs: ['canvas.undo'],
  inputSchema: z.object({
    projectId: z.string().min(1),
    edgeId: z.string().min(1),
  }).strict(),
  outputSchema: capabilityOutputSchema({
    projectId: z.string(),
    edgeId: z.string(),
    undoRef: z.string(),
  }),
  concurrencyKey: 'canvas',
  resolveConcurrencyKey: (input) => `canvas:${input.projectId}`,
  resolveTargetIds: (input) => target(input.projectId, { edgeId: input.edgeId }),
  summarize: (output) => `已断开画布连接 ${output.edgeId}。`,
  createUndo: (output) => ({ kind: 'canvas_history', token: output.undoRef }),
  control: { execution: { mode: 'immediate', cancelable: false, resultState: 'completed' }, impacts: [{
    effect: 'delete', entityTypes: ['canvas.edge'], propertyIds: [], revisionScopes: ['canvas'], verificationRequired: true,
  }] },
})

export const CANVAS_MUTATION_APPLICATION_CAPABILITIES: ApplicationCapabilityDefinition[] = [
  addCanvasNode,
  addAssetToCanvas,
  connectCanvasNodes,
  focusCanvasNode,
  undoCanvasChange,
  redoCanvasChange,
  duplicateCanvasNode,
  updateCanvasNode,
  deleteCanvasNodes,
  selectCanvasNode,
  groupCanvasNodes,
  ungroupCanvasNode,
  clearCanvas,
  disconnectCanvasEdge,
]
