import { z } from 'zod'
import { applicationSchemaRefSchema } from '../../application-control'

import type { ApplicationCapabilityDefinition } from '../applicationCapabilities'
import {
  capabilityControl,
  capabilityOutputSchema,
  defineApplicationCapability,
} from './defineApplicationCapability'

const switchWorkspace = defineApplicationCapability({
  id: 'switch_workspace',
  version: 1,
  title: '切换工作区',
  description: '切换到生成、画布、工具或素材工作区。',
  domain: 'navigation',
  aliases: ['切换页面', '打开工作区', 'switch workspace'],
  readOnly: false,
  control: capabilityControl('navigate', ['application.surface']),
  risk: 'R0',
  dataClasses: ['C0'],
  permission: 'navigation:write',
  idempotent: true,
  destructive: false,
  timeoutMs: 5_000,
  supportsPreview: false,
  supportsUndo: false,
  requiredScopes: ['navigation'],
  producesRefs: ['application.surface'],
  inputSchema: z.object({
    workspaceId: z.enum(['generation', 'nodes', 'tools', 'assets']),
  }).strict(),
  outputSchema: capabilityOutputSchema({ workspace: z.string() }),
  concurrencyKey: 'navigation',
  resolveTargetIds: (input) => ({ workspaceId: input.workspaceId }),
  summarize: (output) => `已切换到 ${output.workspace} 工作区。`,
})

const searchModels = defineApplicationCapability({
  id: 'search_models',
  version: 1,
  title: '搜索生成模型',
  description: '按模型名称、媒体类型、供应商和能力标签搜索生成模型目录。',
  domain: 'models',
  aliases: ['查找模型', '便宜的模型', '图片模型', 'search models'],
  readOnly: true,
  control: capabilityControl('observe', ['generation.model']),
  risk: 'R0',
  dataClasses: ['C0'],
  permission: 'model_catalog:read',
  idempotent: true,
  destructive: false,
  timeoutMs: 5_000,
  supportsPreview: false,
  supportsUndo: false,
  requiredScopes: [],
  producesRefs: ['generation.model'],
  inputSchema: z.object({
    query: z.string().max(500).default(''),
    mediaType: z.enum(['image', 'video', 'audio']).optional(),
    providerId: z.string().min(1).optional(),
    tags: z.array(z.string().min(1).max(100)).max(8).optional(),
    sortBy: z.enum(['registry', 'recommended', 'lowest_estimated_price']).optional(),
    cursor: z.number().int().nonnegative().default(0),
    limit: z.number().int().min(1).max(50).default(32),
  }).strict(),
  outputSchema: capabilityOutputSchema({
    catalogVersion: z.string(),
    models: z.array(z.record(z.string(), z.unknown())),
    nextCursor: z.number().int().nonnegative().nullable(),
  }),
  concurrencyKey: 'model_catalog',
  summarize: (output) => `模型目录搜索返回 ${output.models.length} 项。`,
})

const getModelSchema = defineApplicationCapability({
  id: 'get_model_schema',
  version: 1,
  title: '读取模型参数结构',
  description: '读取单个生成模型的能力标签、价格估算和参数结构。',
  domain: 'models',
  aliases: ['模型参数', '模型支持什么', 'get model schema'],
  readOnly: true,
  control: capabilityControl('observe', ['generation.model']),
  risk: 'R0',
  dataClasses: ['C0'],
  permission: 'model_catalog:read',
  idempotent: true,
  destructive: false,
  timeoutMs: 5_000,
  supportsPreview: false,
  supportsUndo: false,
  requiredScopes: [],
  acceptsRefs: ['generation.model'],
  producesRefs: ['generation.model'],
  inputSchema: z.object({ modelId: z.string().min(1) }).strict(),
  outputSchema: capabilityOutputSchema({
    schemaVersion: z.string(),
    schemaRef: applicationSchemaRefSchema,
    meta: z.record(z.string(), z.unknown()),
    params: z.array(z.record(z.string(), z.unknown())),
  }),
  concurrencyKey: 'model_schema',
  resolveConcurrencyKey: (input) => `model_schema:${input.modelId}`,
  resolveTargetIds: (input) => ({ modelId: input.modelId }),
  summarize: (output) => `已读取模型 ${String(output.meta.id ?? '')} 的参数结构。`,
})

const prepareGenerationTask = defineApplicationCapability({
  id: 'prepare_generation_task',
  version: 1,
  title: '校验生成参数',
  description: '在提交前验证模型、媒体类型、必填项、参数范围和联动结果。',
  domain: 'generation',
  aliases: ['检查生成参数', '准备生成', 'prepare generation'],
  readOnly: true,
  control: capabilityControl('observe', ['generation.preparation']),
  risk: 'R0',
  dataClasses: ['C1'],
  permission: 'generation:prepare',
  idempotent: true,
  destructive: false,
  timeoutMs: 5_000,
  supportsPreview: false,
  supportsUndo: false,
  requiredScopes: [],
  acceptsRefs: ['generation.model'],
  producesRefs: ['generation.preparation'],
  inputSchema: z.object({
    modelId: z.string().min(1),
    prompt: z.string().max(32 * 1024),
    mediaType: z.enum(['image', 'video', 'audio']),
    params: z.record(z.string(), z.unknown()).optional(),
  }).strict(),
  outputSchema: capabilityOutputSchema({
    preparation: z.object({
      prepared: z.literal(true),
      modelId: z.string().min(1),
      providerId: z.string().min(1),
      mediaType: z.enum(['image', 'video', 'audio']),
      options: z.record(z.string(), z.unknown()),
    }).passthrough(),
  }),
  concurrencyKey: 'generation_prepare',
  resolveConcurrencyKey: (input) => `generation_prepare:${input.modelId}`,
  resolveTargetIds: (input) => ({ modelId: input.modelId }),
  summarize: (output) => `模型 ${output.preparation.modelId} 的生成参数已通过校验。`,
})

const createVisibleGenerationTask = defineApplicationCapability({
  id: 'create_visible_generation_task',
  version: 1,
  title: '创建可见生成任务',
  description: '在生成工作区创建用户可见的图片、视频或音频生成任务。',
  domain: 'generation',
  aliases: ['生成图片', '生成视频', '生成音频', 'create generation'],
  readOnly: false,
  control: capabilityControl('execute', ['generation.task'], {
    revisionScopes: ['generation'], verificationRequired: false, resultState: 'submitted',
  }),
  risk: 'R2',
  dataClasses: ['C1'],
  permission: 'generation:create',
  idempotent: true,
  destructive: false,
  timeoutMs: 60_000,
  supportsPreview: true,
  supportsUndo: false,
  completionKind: 'submitted',
  requiredScopes: ['generation'],
  acceptsRefs: ['generation.model', 'asset'],
  producesRefs: ['generation.task'],
  successEvidence: [
    '返回稳定 taskId、submitted 状态和最新 generation revision。',
    '该结果只证明任务已提交；生成完成必须由后续状态证据确认。',
  ],
  inputSchema: z.object({
    modelId: z.string().min(1),
    prompt: z.string().max(32 * 1024),
    mediaType: z.enum(['image', 'video', 'audio']),
    params: z.record(z.string(), z.unknown()).optional(),
  }).strict(),
  outputSchema: capabilityOutputSchema({
    taskId: z.string().min(1),
    status: z.literal('submitted'),
  }),
  concurrencyKey: 'generation',
  resolveConcurrencyKey: (input) => `generation:${input.modelId}`,
  resolveTargetIds: (input) => ({ modelId: input.modelId }),
  preview: (input) => ({
    title: '创建生成任务',
    summary: `使用模型 ${input.modelId} 创建 ${input.mediaType} 任务；提示词长度 ${input.prompt.length}。`,
    targetIds: { modelId: input.modelId },
    reversible: false,
    dataClasses: ['C1'],
    destination: '已配置的生成模型 Provider',
  }),
  summarize: (output) => `生成任务 ${output.taskId} 已提交，当前尚不能视为生成成功。`,
})

const getGenerationTask = defineApplicationCapability({
  id: 'get_generation_task',
  version: 1,
  title: '读取生成任务',
  description: '按明确任务引用读取生成状态、错误摘要和恢复约束。',
  domain: 'generation',
  aliases: ['生成进度', '任务状态', 'get generation task'],
  readOnly: true,
  control: capabilityControl('observe', ['generation.task', 'generation.result']),
  risk: 'R0',
  dataClasses: ['C1'],
  permission: 'generation:read',
  idempotent: true,
  destructive: false,
  timeoutMs: 5_000,
  supportsPreview: false,
  supportsUndo: false,
  requiredScopes: ['generation'],
  acceptsRefs: ['generation.task'],
  producesRefs: ['generation.task', 'generation.result'],
  inputSchema: z.object({ taskId: z.string().min(1) }).strict(),
  outputSchema: capabilityOutputSchema({
    task: z.record(z.string(), z.unknown()),
  }),
  concurrencyKey: 'generation',
  resolveConcurrencyKey: (input) => `generation:${input.taskId}`,
  resolveTargetIds: (input) => ({ taskId: input.taskId }),
  resolveObservedEffects: (input, output) => {
    const status = typeof output.task.status === 'string' ? output.task.status : 'unknown'
    const terminal = ['success', 'completed', 'error', 'failed', 'cancelled', 'canceled'].includes(status)
    return [{
      effect: 'observe',
      entityTypes: ['generation.task', ...(status === 'success' || status === 'completed'
        ? ['generation.result'] : [])],
      propertyIds: [],
      targetRefs: [{ kind: 'generation.task', id: input.taskId }],
      count: 1,
      verified: terminal,
      evidence: [],
    }]
  },
  summarize: (output) => `生成任务状态：${String(output.task.status ?? 'unknown')}。`,
})

const cancelGenerationTask = defineApplicationCapability({
  id: 'cancel_generation_task',
  version: 1,
  title: '取消生成任务',
  description: '取消明确任务引用对应的可取消生成任务。',
  domain: 'generation',
  aliases: ['停止生成', '取消任务', 'cancel generation'],
  readOnly: false,
  control: capabilityControl('execute', ['generation.task'], { revisionScopes: ['generation'] }),
  risk: 'R2',
  dataClasses: ['C1'],
  permission: 'generation:cancel',
  idempotent: true,
  destructive: true,
  timeoutMs: 10_000,
  supportsPreview: true,
  supportsUndo: false,
  requiredScopes: ['generation'],
  acceptsRefs: ['generation.task'],
  producesRefs: ['generation.task'],
  inputSchema: z.object({
    taskId: z.string().min(1),
    reason: z.string().min(1).max(500),
  }).strict(),
  outputSchema: capabilityOutputSchema({
    taskId: z.string().min(1),
    status: z.string().min(1),
  }),
  concurrencyKey: 'generation',
  resolveConcurrencyKey: (input) => `generation:${input.taskId}`,
  resolveTargetIds: (input) => ({ taskId: input.taskId }),
  preview: (input) => ({
    title: '取消生成任务',
    summary: `取消任务 ${input.taskId}。`,
    targetIds: { taskId: input.taskId },
    reversible: false,
    dataClasses: ['C1'],
  }),
  summarize: (output) => `任务 ${output.taskId} 的取消状态为 ${output.status}。`,
})

export const GENERATION_APPLICATION_CAPABILITIES: ApplicationCapabilityDefinition[] = [
  switchWorkspace,
  searchModels,
  getModelSchema,
  prepareGenerationTask,
  createVisibleGenerationTask,
  getGenerationTask,
  cancelGenerationTask,
]
