function createCanvasScenes(context) {
  const {
    setupCanvas,
    setupCanvasImageCapabilityToolbar,
    setupCanvasPanoramaToolbar,
    setupCanvasRelightEditor,
    setupCanvasMultiAngleEditor,
    setupCanvasUpscaleNode,
    setupCanvasPortraitTextureNode,
    setupCanvasElementEditNode,
    setupCanvasMultiLayerDocumentEditor,
    setupCanvasGpuFiveLayerPerformance,
    setupCanvasNineGrid,
    setupCanvasPanoramaViewer,
    setupCanvasMidjourneyNode,
    setupCanvasGptMaskEditor,
    setupCanvasAssetGroup,
    setupCanvasBatchConnection,
    setupCanvasAssetGroupRemoveConfirmation,
    setupCanvasQuickConnectPrompt,
  } = context

  return [
    { id: 'canvas-projects', surface: '画布', name: '画布-项目列表', setup: setupCanvas },
    {
      id: 'canvas-image-capability-toolbar',
      surface: '画布',
      writesUserData: true,
      name: '画布-图片能力工具条信息架构',
      setup: setupCanvasImageCapabilityToolbar,
    },
    {
      id: 'canvas-panorama-toolbar',
      surface: '画布',
      writesUserData: true,
      name: '画布-720°全景工具条与相邻节点',
      setup: setupCanvasPanoramaToolbar,
    },
    {
      id: 'canvas-panorama-viewer',
      surface: '画布',
      writesUserData: true,
      name: '画布-全景查看节点与沉浸式查看器',
      setup: setupCanvasPanoramaViewer,
    },
    {
      id: 'canvas-relight-editor',
      surface: '画布',
      writesUserData: true,
      name: '画布-图片打光节点内可视化工作台',
      setup: setupCanvasRelightEditor,
    },
    {
      id: 'canvas-multi-angle-editor',
      surface: '画布',
      writesUserData: true,
      name: '画布-多角度节点内相机工作台',
      setup: setupCanvasMultiAngleEditor,
    },
    {
      id: 'canvas-upscale-node',
      surface: '画布',
      writesUserData: true,
      name: '画布-高清放大节点与保存重开',
      setup: setupCanvasUpscaleNode,
    },
    {
      id: 'canvas-portrait-texture-node',
      surface: '画布',
      writesUserData: true,
      name: '画布-人像质感节点与保存重开',
      setup: setupCanvasPortraitTextureNode,
    },
    {
      id: 'canvas-element-edit-node',
      surface: '画布',
      writesUserData: true,
      name: '画布-局部重绘节点内遮罩工作台',
      setup: setupCanvasElementEditNode,
    },
    {
      id: 'canvas-gpu-five-layer-performance',
      surface: '画布',
      writesUserData: true,
      name: '画布-固定KIE五层GPU拖动基准',
      setup: setupCanvasGpuFiveLayerPerformance,
    },
    {
      id: 'canvas-multi-layer-document-editor',
      surface: '画布',
      writesUserData: true,
      name: '画布-多图层图片文档编辑器',
      setup: setupCanvasMultiLayerDocumentEditor,
    },
    {
      id: 'canvas-nine-grid',
      surface: '画布',
      writesUserData: true,
      name: '画布-固定九宫格预设与本地宫格切分',
      setup: setupCanvasNineGrid,
    },
    {
      id: 'canvas-midjourney-node',
      surface: '画布',
      writesUserData: true,
      name: '画布-Midjourney 节点与端口',
      setup: async (page) => setupCanvasMidjourneyNode(page, false),
    },
    {
      id: 'canvas-midjourney-settings',
      surface: '画布',
      writesUserData: true,
      name: '画布-Midjourney 参数特殊面板',
      setup: async (page) => setupCanvasMidjourneyNode(page, true),
    },
    {
      id: 'canvas-gpt-mask-editor',
      surface: '画布',
      writesUserData: true,
      name: '画布-GPT Image 2 遮罩编辑器',
      setup: setupCanvasGptMaskEditor,
    },
    {
      id: 'canvas-asset-group-collapsed',
      surface: '画布',
      writesUserData: true,
      name: '画布-素材组折叠与束线',
      setup: async (page) => setupCanvasAssetGroup(page, false),
    },
    {
      id: 'canvas-asset-group-expanded',
      surface: '画布',
      writesUserData: true,
      name: '画布-素材组管理工作面',
      setup: async (page) => setupCanvasAssetGroup(page, true),
    },
    {
      id: 'canvas-asset-group-remove-confirmation',
      surface: '画布',
      writesUserData: true,
      name: '画布-素材组移出确认',
      setup: setupCanvasAssetGroupRemoveConfirmation,
    },
    {
      id: 'canvas-batch-connection',
      surface: '画布',
      writesUserData: true,
      name: '画布-框选素材批量拖连',
      setup: setupCanvasBatchConnection,
    },
    {
      id: 'canvas-quick-connect-prompt',
      surface: '画布',
      name: '画布-拖放建节点与提示词换行',
      writesUserData: true,
      setup: setupCanvasQuickConnectPrompt,
    },
  ]
}

module.exports = { createCanvasScenes }
