struct Params { operation: vec4f, maskOptions: vec4f, slopes0: vec4f, slopes1: vec4f }
@group(0) @binding(0) var sourceTexture: texture_2d<f32>;
@group(0) @binding(1) var maskTexture: texture_2d<f32>;
@group(0) @binding(2) var curveTexture: texture_2d<f32>;
@group(0) @binding(3) var<uniform> params: Params;
fn encodeSrgb(v:f32)->f32{let m=abs(v);return sign(v)*select(12.92*m,1.055*pow(m,1.0/2.4)-0.055,m>0.0031308);}
fn decodeSrgb(v:f32)->f32{let m=abs(v);return sign(v)*select(m/12.92,pow((m+0.055)/1.055,2.4),m>0.04045);}
fn curveSlope(row:i32,right:bool)->f32{if(row==0){return select(params.slopes0.x,params.slopes0.y,right);}if(row==1){return select(params.slopes0.z,params.slopes0.w,right);}if(row==2){return select(params.slopes1.x,params.slopes1.y,right);}return select(params.slopes1.z,params.slopes1.w,right);}
fn sampleCurve(row:i32,input:f32)->f32{let last=4095.0; if(input<0.0){return textureLoad(curveTexture,vec2i(0,row),0).r+input*curveSlope(row,false);} if(input>1.0){return textureLoad(curveTexture,vec2i(4095,row),0).r+(input-1.0)*curveSlope(row,true);} let position=input*last;let lo=i32(floor(position));let hi=min(4095,lo+1);return mix(textureLoad(curveTexture,vec2i(lo,row),0).r,textureLoad(curveTexture,vec2i(hi,row),0).r,fract(position));}
fn blendChannel(b:f32,s:f32,mode:u32)->f32{if(mode==1u){return b*s;}if(mode==2u){return b+s-b*s;}if(mode==3u){return select(2.0*b*s,1.0-2.0*(1.0-b)*(1.0-s),b>0.5);}if(mode==4u){if(s<=0.5){return b-(1.0-2.0*s)*b*(1.0-b);}let d=select(((16.0*b-12.0)*b+4.0)*b,sqrt(max(0.0,b)),b>0.25);return b+(2.0*s-1.0)*(d-b);}return s;}
fn maskAt(c:vec2i)->f32{if(params.maskOptions.x<0.5){return params.maskOptions.y;}let s=vec2i(textureDimensions(maskTexture));var v=params.maskOptions.y;if(all(c>=vec2i(0))&&all(c<s)){v=textureLoad(maskTexture,c,0).r;}return select(v,1.0-v,params.maskOptions.z>0.5);}
@vertex fn vs_main(@builtin(vertex_index)vi:u32)->@builtin(position)vec4f{let p=array<vec2f,3>(vec2f(-1),vec2f(3,-1),vec2f(-1,3));return vec4f(p[vi],0,1);}
@fragment fn fs_main(@builtin(position)position:vec4f)->@location(0)vec4f{let source=textureLoad(sourceTexture,vec2i(position.xy),0);if(source.a<=0.0){return source;}let original=source.rgb/source.a;let perceptual=vec3f(encodeSrgb(original.r),encodeSrgb(original.g),encodeSrgb(original.b));let adjusted=vec3f(sampleCurve(0,sampleCurve(1,perceptual.r)),sampleCurve(0,sampleCurve(2,perceptual.g)),sampleCurve(0,sampleCurve(3,perceptual.b)));let masked=mix(perceptual,adjusted,maskAt(vec2i(position.xy)));let mode=u32(params.operation.y);let blended=vec3f(blendChannel(perceptual.r,masked.r,mode),blendChannel(perceptual.g,masked.g,mode),blendChannel(perceptual.b,masked.b,mode));let output=mix(perceptual,blended,params.operation.x);let linear=vec3f(decodeSrgb(output.r),decodeSrgb(output.g),decodeSrgb(output.b));return vec4f(linear*source.a,source.a);}
