const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { test } = require('node:test')
const { normalizeReport, compareBaseline, check } = require('./check-dead-code.cjs')

test('新增文件/依赖均失败，导出只报告，删减可通过', () => {
  const current = normalizeReport({ issues: [{ file: 'package.json', dependencies: [{ name: 'unused-dependency' }], exports: [{ name: 'exportOnly' }], files: [{ name: 'unused.ts' }] }] })
  assert.deepEqual(compareBaseline(current, { files: [], dependencies: [] }), ['新增未使用 files: unused.ts', '新增未使用 dependencies: package.json:unused-dependency'])
  assert.deepEqual(compareBaseline({ files: [], dependencies: [] }, current), [])
  assert.equal(current.exports, 1)
  assert.throws(() => normalizeReport({}), /有效 issues/)
})
test('真实 Knip 检测孤立文件/依赖；写回拒绝新增且保持基线不变', t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'henji-dead-code-'))
  t.after(() => fs.rmSync(root, { recursive: true, force: true }))
  fs.writeFileSync(path.join(root, 'package.json'), JSON.stringify({ name: 'dead-code-fixture', private: true, dependencies: { 'unused-fixture-dependency': '1.0.0' } }))
  fs.writeFileSync(path.join(root, 'knip.json'), JSON.stringify({ entry: ['entry.ts'], project: ['*.ts'] }))
  fs.writeFileSync(path.join(root, 'entry.ts'), "export const used = true\n")
  fs.writeFileSync(path.join(root, 'orphan.ts'), "export const orphan = true\n")
  const baseline = path.join(root, 'baseline.json')
  const empty = { version: 1, files: [], dependencies: [] }
  fs.writeFileSync(baseline, JSON.stringify(empty))
  const before = fs.readFileSync(baseline, 'utf8')
  const result = check(root, baseline, true)
  assert.ok(result.errors.includes('新增未使用 files: orphan.ts'))
  assert.ok(result.errors.includes('新增未使用 dependencies: package.json:unused-fixture-dependency'))
  assert.equal(fs.readFileSync(baseline, 'utf8'), before)
  fs.writeFileSync(baseline, JSON.stringify({ ...empty, files: result.files, dependencies: result.dependencies }))
  fs.unlinkSync(path.join(root, 'orphan.ts'))
  fs.writeFileSync(path.join(root, 'package.json'), JSON.stringify({ name: 'dead-code-fixture', private: true }))
  assert.deepEqual(check(root, baseline, true).errors, [])
  assert.deepEqual(JSON.parse(fs.readFileSync(baseline, 'utf8')).files, [])
  assert.deepEqual(JSON.parse(fs.readFileSync(baseline, 'utf8')).dependencies, [])
})
