export { detectShell, isDesktopRuntime, getPlatform } from './runtime'
export type { ShellKind } from './types'
export { PlatformNotImplementedError } from './types'
export type { PlatformRuntime } from './contracts'
export * from './contracts'
